import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class KoreystiliReading extends StatefulWidget {
  final int page;
  const KoreystiliReading({super.key, required this.page});

  @override
  State<KoreystiliReading> createState() => _KoreystiliReadingState();
}

class _KoreystiliReadingState extends State<KoreystiliReading> {
  List<String> images = [
    'https://i.ibb.co/W63KRqt/Mel-Book-Koreys-tili-A5-Page1.jpg',
    'https://i.ibb.co/XsVFYXq/Mel-Book-Koreys-tili-A5-Page2.jpg',
    'https://i.ibb.co/sK5mMLv/Mel-Book-Koreys-tili-A5-Page3.jpg',
    'https://i.ibb.co/7zZKHvy/Mel-Book-Koreys-tili-A5-Page4.jpg',
    'https://i.ibb.co/SPwp2gN/Mel-Book-Koreys-tili-A5-Page5.jpg',
    'https://i.ibb.co/m59G2xz/Mel-Book-Koreys-tili-A5-Page6.jpg',
    'https://i.ibb.co/7Jp24V6/Mel-Book-Koreys-tili-A5-Page7.jpg',
    'https://i.ibb.co/hZJqkMP/Mel-Book-Koreys-tili-A5-Page8.jpg',
    'https://i.ibb.co/M5d89CG/Mel-Book-Koreys-tili-A5-Page9.jpg',
    'https://i.ibb.co/f9rzd84/Mel-Book-Koreys-tili-A5-Page10.jpg',
    'https://i.ibb.co/bLcJdhx/Mel-Book-Koreys-tili-A5-Page11.jpg',
    'https://i.ibb.co/BK7Nsyz/Mel-Book-Koreys-tili-A5-Page12.jpg',
    'https://i.ibb.co/p0F3KNw/Mel-Book-Koreys-tili-A5-Page13.jpg',
    'https://i.ibb.co/S3Bm5Mq/Mel-Book-Koreys-tili-A5-Page14.jpg',
    'https://i.ibb.co/j5pcsPx/Mel-Book-Koreys-tili-A5-Page15.jpg',
    'https://i.ibb.co/VM8c2sF/Mel-Book-Koreys-tili-A5-Page16.jpg',
    'https://i.ibb.co/jb1qhTt/Mel-Book-Koreys-tili-A5-Page17.jpg',
    'https://i.ibb.co/grvSsfB/Mel-Book-Koreys-tili-A5-Page18.jpg',
    'https://i.ibb.co/bzVsCLK/Mel-Book-Koreys-tili-A5-Page19.jpg',
    'https://i.ibb.co/3vXP9Cb/Mel-Book-Koreys-tili-A5-Page20.jpg',
    'https://i.ibb.co/bK6Z9X2/Mel-Book-Koreys-tili-A5-Page21.jpg',
    'https://i.ibb.co/Cw20HKV/Mel-Book-Koreys-tili-A5-Page22.jpg',
    'https://i.ibb.co/Lpqg1sb/Mel-Book-Koreys-tili-A5-Page23.jpg',
    'https://i.ibb.co/m4h2c4d/Mel-Book-Koreys-tili-A5-Page24.jpg',
    'https://i.ibb.co/6HQN7Rz/Mel-Book-Koreys-tili-A5-Page25.jpg',
    'https://i.ibb.co/C2NTtJG/Mel-Book-Koreys-tili-A5-Page26.jpg',
    'https://i.ibb.co/hFWdmjs/Mel-Book-Koreys-tili-A5-Page27.jpg',
    'https://i.ibb.co/71jWX8c/Mel-Book-Koreys-tili-A5-Page28.jpg',
    'https://i.ibb.co/tB8wYhv/Mel-Book-Koreys-tili-A5-Page29.jpg',
    'https://i.ibb.co/RgBGFBG/Mel-Book-Koreys-tili-A5-Page30.jpg',
    'https://i.ibb.co/7X9PRHD/Mel-Book-Koreys-tili-A5-Page31.jpg',
    'https://i.ibb.co/1v32Sck/Mel-Book-Koreys-tili-A5-Page32.jpg',
    'https://i.ibb.co/42SgN4Y/Mel-Book-Koreys-tili-A5-Page33.jpg',
    'https://i.ibb.co/2Sp4tvD/Mel-Book-Koreys-tili-A5-Page34.jpg',
    'https://i.ibb.co/fXdsZRX/Mel-Book-Koreys-tili-A5-Page35.jpg',
    'https://i.ibb.co/WBv4GG4/Mel-Book-Koreys-tili-A5-Page36.jpg',
    'https://i.ibb.co/jTSkTjj/Mel-Book-Koreys-tili-A5-Page37.jpg',
    'https://i.ibb.co/mF3SR3s/Mel-Book-Koreys-tili-A5-Page38.jpg',
    'https://i.ibb.co/x712mVX/Mel-Book-Koreys-tili-A5-Page39.jpg',
    'https://i.ibb.co/8249xT6/Mel-Book-Koreys-tili-A5-Page40.jpg',
    'https://i.ibb.co/FWQpQrr/Mel-Book-Koreys-tili-A5-Page41.jpg',
    'https://i.ibb.co/DwvFd7R/Mel-Book-Koreys-tili-A5-Page42.jpg',
    'https://i.ibb.co/4ffYmdF/Mel-Book-Koreys-tili-A5-Page43.jpg',
    'https://i.ibb.co/bJWnJQC/Mel-Book-Koreys-tili-A5-Page44.jpg',
    'https://i.ibb.co/jbh2W6y/Mel-Book-Koreys-tili-A5-Page45.jpg',
    'https://i.ibb.co/TBLLBcD/Mel-Book-Koreys-tili-A5-Page46.jpg',
    'https://i.ibb.co/GMCbn06/Mel-Book-Koreys-tili-A5-Page47.jpg',
    'https://i.ibb.co/L1qkmkw/Mel-Book-Koreys-tili-A5-Page48.jpg',
    'https://i.ibb.co/GMshtj1/Mel-Book-Koreys-tili-A5-Page49.jpg',
    'https://i.ibb.co/k0CHpft/Mel-Book-Koreys-tili-A5-Page50.jpg',
    'https://i.ibb.co/PY651GQ/Mel-Book-Koreys-tili-A5-Page51.jpg',
    'https://i.ibb.co/q5jL8pQ/Mel-Book-Koreys-tili-A5-Page52.jpg',
    'https://i.ibb.co/SrzF27f/Mel-Book-Koreys-tili-A5-Page53.jpg',
    'https://i.ibb.co/ZLtcnZB/Mel-Book-Koreys-tili-A5-Page54.jpg',
    'https://i.ibb.co/dKdBDqK/Mel-Book-Koreys-tili-A5-Page55.jpg',
    'https://i.ibb.co/zxbcgYQ/Mel-Book-Koreys-tili-A5-Page56.jpg',
    'https://i.ibb.co/LCznkQd/Mel-Book-Koreys-tili-A5-Page57.jpg',
    'https://i.ibb.co/3d4pyYK/Mel-Book-Koreys-tili-A5-Page58.jpg',
    'https://i.ibb.co/X7ykZ47/Mel-Book-Koreys-tili-A5-Page59.jpg',
    'https://i.ibb.co/g4BgJpB/Mel-Book-Koreys-tili-A5-Page60.jpg',
    'https://i.ibb.co/3sQHxkC/Mel-Book-Koreys-tili-A5-Page61.jpg',
    'https://i.ibb.co/cYyd1Jk/Mel-Book-Koreys-tili-A5-Page62.jpg',
    'https://i.ibb.co/XshR4VM/Mel-Book-Koreys-tili-A5-Page63.jpg',
    'https://i.ibb.co/NLvW4Sd/Mel-Book-Koreys-tili-A5-Page64.jpg',
    'https://i.ibb.co/q1BYyqm/Mel-Book-Koreys-tili-A5-Page65.jpg',
    'https://i.ibb.co/prqBsC5/Mel-Book-Koreys-tili-A5-Page66.jpg',
    'https://i.ibb.co/sQm0gdg/Mel-Book-Koreys-tili-A5-Page67.jpg',
    'https://i.ibb.co/DgQXWmW/Mel-Book-Koreys-tili-A5-Page68.jpg',
    'https://i.ibb.co/phbbryC/Mel-Book-Koreys-tili-A5-Page69.jpg',
    'https://i.ibb.co/PwJmYXv/Mel-Book-Koreys-tili-A5-Page70.jpg',
    'https://i.ibb.co/5j82TsJ/Mel-Book-Koreys-tili-A5-Page71.jpg',
    'https://i.ibb.co/4Zn69CX/Mel-Book-Koreys-tili-A5-Page72.jpg',
    'https://i.ibb.co/gMXr76c/Mel-Book-Koreys-tili-A5-Page73.jpg',
    'https://i.ibb.co/tLV2XQw/Mel-Book-Koreys-tili-A5-Page74.jpg',
    'https://i.ibb.co/fQFGL90/Mel-Book-Koreys-tili-A5-Page75.jpg',
    'https://i.ibb.co/F4SQ0KB/Mel-Book-Koreys-tili-A5-Page76.jpg',
    'https://i.ibb.co/s1kFMQR/Mel-Book-Koreys-tili-A5-Page77.jpg',
    'https://i.ibb.co/WPSW4TC/Mel-Book-Koreys-tili-A5-Page78.jpg',
    'https://i.ibb.co/YkJCqrm/Mel-Book-Koreys-tili-A5-Page79.jpg',
    'https://i.ibb.co/1f5wHvQ/Mel-Book-Koreys-tili-A5-Page80.jpg',
    'https://i.ibb.co/KjfDDZS/Mel-Book-Koreys-tili-A5-Page81.jpg',
    'https://i.ibb.co/xH8gDTV/Mel-Book-Koreys-tili-A5-Page82.jpg',
    'https://i.ibb.co/gwGJjvM/Mel-Book-Koreys-tili-A5-Page83.jpg',
    'https://i.ibb.co/BV8LgF2/Mel-Book-Koreys-tili-A5-Page84.jpg',
    'https://i.ibb.co/TgzCJjZ/Mel-Book-Koreys-tili-A5-Page86.jpg',
    'https://i.ibb.co/d5VNrBt/Mel-Book-Koreys-tili-A5-Page85.jpg',
    'https://i.ibb.co/ryNCcmt/Mel-Book-Koreys-tili-A5-Page87.jpg',
    'https://i.ibb.co/jkqKBg1/Mel-Book-Koreys-tili-A5-Page88.jpg',
    'https://i.ibb.co/6tTKJz7/Mel-Book-Koreys-tili-A5-Page89.jpg',
    'https://i.ibb.co/86fKsX4/Mel-Book-Koreys-tili-A5-Page90.jpg',
    'https://i.ibb.co/6PTM3rk/Mel-Book-Koreys-tili-A5-Page91.jpg',
    'https://i.ibb.co/yP0H0w3/Mel-Book-Koreys-tili-A5-Page92.jpg',
    'https://i.ibb.co/NLM2BgP/Mel-Book-Koreys-tili-A5-Page93.jpg',
    'https://i.ibb.co/SRq7Yh1/Mel-Book-Koreys-tili-A5-Page94.jpg',
    'https://i.ibb.co/pnNYdCb/Mel-Book-Koreys-tili-A5-Page95.jpg',
    'https://i.ibb.co/YPQBZ1H/Mel-Book-Koreys-tili-A5-Page96.jpg',
    'https://i.ibb.co/K7BHyBP/Mel-Book-Koreys-tili-A5-Page97.jpg',
    'https://i.ibb.co/2qzgZdt/Mel-Book-Koreys-tili-A5-Page98.jpg',
    'https://i.ibb.co/SV1LvJv/Mel-Book-Koreys-tili-A5-Page99.jpg',
    'https://i.ibb.co/qBgVmTz/Mel-Book-Koreys-tili-A5-Page100.jpg',
    'https://i.ibb.co/ZXQ68HR/Mel-Book-Koreys-tili-A5-Page101.jpg',
    'https://i.ibb.co/LCCjhvY/Mel-Book-Koreys-tili-A5-Page102.jpg',
    'https://i.ibb.co/XV5Mk3J/Mel-Book-Koreys-tili-A5-Page103.jpg',
    'https://i.ibb.co/QPnXmhB/Mel-Book-Koreys-tili-A5-Page104.jpg',
    'https://i.ibb.co/JnWsByw/Mel-Book-Koreys-tili-A5-Page105.jpg'
    'https://i.ibb.co/Gcq8JDD/Mel-Book-Koreys-tili-A5-Page106.jpg',
    'https://i.ibb.co/0Zr6Lv3/Mel-Book-Koreys-tili-A5-Page107.jpg',
    'https://i.ibb.co/nmYTqtg/Mel-Book-Koreys-tili-A5-Page108.jpg',
    'https://i.ibb.co/1MMn0Q6/Mel-Book-Koreys-tili-A5-Page109.jpg',
    'https://i.ibb.co/xfqzMNb/Mel-Book-Koreys-tili-A5-Page110.jpg',
    'https://i.ibb.co/mhbCKCy/Mel-Book-Koreys-tili-A5-Page111.jpg',
    'https://i.ibb.co/ncbySw6/Mel-Book-Koreys-tili-A5-Page112.jpg',
    'https://i.ibb.co/MRwS8pY/Mel-Book-Koreys-tili-A5-Page113.jpg',
    'https://i.ibb.co/pxVxmJx/Mel-Book-Koreys-tili-A5-Page114.jpg',
    'https://i.ibb.co/92538Tx/Mel-Book-Koreys-tili-A5-Page115.jpg',
    'https://i.ibb.co/kQRVrvV/Mel-Book-Koreys-tili-A5-Page116.jpg',
    'https://i.ibb.co/b2Xx0Zk/Mel-Book-Koreys-tili-A5-Page117.jpg',
    'https://i.ibb.co/D8JQsb8/Mel-Book-Koreys-tili-A5-Page118.jpg',
    'https://i.ibb.co/Fw955Wn/Mel-Book-Koreys-tili-A5-Page119.jpg',
    'https://i.ibb.co/8jn3vqK/Mel-Book-Koreys-tili-A5-Page120.jpg',
    'https://i.ibb.co/JtmRt0n/Mel-Book-Koreys-tili-A5-Page121.jpg',
    'https://i.ibb.co/cwP5gRY/Mel-Book-Koreys-tili-A5-Page122.jpg',
    'https://i.ibb.co/6B2XjKM/Mel-Book-Koreys-tili-A5-Page123.jpg',
    'https://i.ibb.co/fds7BSr/Mel-Book-Koreys-tili-A5-Page124.jpg',
    'https://i.ibb.co/TYQqJJH/Mel-Book-Koreys-tili-A5-Page125.jpg',
    'https://i.ibb.co/tLvVp6B/Mel-Book-Koreys-tili-A5-Page126.jpg',
    'https://i.ibb.co/SnNYhyH/Mel-Book-Koreys-tili-A5-Page127.jpg',
    'https://i.ibb.co/YLYLZ3S/Mel-Book-Koreys-tili-A5-Page128.jpg',
    'https://i.ibb.co/x7n82Y1/Mel-Book-Koreys-tili-A5-Page129.jpg',
    'https://i.ibb.co/hFXbHYZ/Mel-Book-Koreys-tili-A5-Page130.jpg',
    'https://i.ibb.co/m5hGqnL/Mel-Book-Koreys-tili-A5-Page131.jpg',
    'https://i.ibb.co/PgSQnjt/Mel-Book-Koreys-tili-A5-Page132.jpg',
    'https://i.ibb.co/y8jLjdJ/Mel-Book-Koreys-tili-A5-Page133.jpg',
    'https://i.ibb.co/ZNqBGBm/Mel-Book-Koreys-tili-A5-Page134.jpg',
    'https://i.ibb.co/0tFYsP3/Mel-Book-Koreys-tili-A5-Page135.jpg',
    'https://i.ibb.co/HzptqmF/Mel-Book-Koreys-tili-A5-Page136.jpg',
    'https://i.ibb.co/h7LsXHk/Mel-Book-Koreys-tili-A5-Page137.jpg',
    'https://i.ibb.co/WKRKq3y/Mel-Book-Koreys-tili-A5-Page138.jpg',
    'https://i.ibb.co/fCLPT5y/Mel-Book-Koreys-tili-A5-Page139.jpg',
    'https://i.ibb.co/PMp62hc/Mel-Book-Koreys-tili-A5-Page140.jpg',
    'https://i.ibb.co/YhbCWYJ/Mel-Book-Koreys-tili-A5-Page141.jpg',
    'https://i.ibb.co/5RSPQtn/Mel-Book-Koreys-tili-A5-Page142.jpg',
    'https://i.ibb.co/d5fxh2d/Mel-Book-Koreys-tili-A5-Page143.jpg',
    'https://i.ibb.co/tHXmm89/Mel-Book-Koreys-tili-A5-Page144.jpg',
    'https://i.ibb.co/QfkM333/Mel-Book-Koreys-tili-A5-Page145.jpg',
    'https://i.ibb.co/2870ML4/Mel-Book-Koreys-tili-A5-Page146.jpg',
    'https://i.ibb.co/XWBCpHB/Mel-Book-Koreys-tili-A5-Page147.jpg',
    'https://i.ibb.co/sWssCnd/Mel-Book-Koreys-tili-A5-Page148.jpg',
    'https://i.ibb.co/mvYJZH5/Mel-Book-Koreys-tili-A5-Page149.jpg',
    'https://i.ibb.co/BBXQbTx/Mel-Book-Koreys-tili-A5-Page150.jpg',
    'https://i.ibb.co/mHxXL0H/Mel-Book-Koreys-tili-A5-Page151.jpg',
    'https://i.ibb.co/CzrMQxb/Mel-Book-Koreys-tili-A5-Page152.jpg',
    'https://i.ibb.co/wr5t6GP/Mel-Book-Koreys-tili-A5-Page153.jpg',
    'https://i.ibb.co/FVfP1C9/Mel-Book-Koreys-tili-A5-Page154.jpg',
    'https://i.ibb.co/yY8vg7P/Mel-Book-Koreys-tili-A5-Page155.jpg',
    'https://i.ibb.co/BGYSCfH/Mel-Book-Koreys-tili-A5-Page156.jpg',
    'https://i.ibb.co/FWvnXcc/Mel-Book-Koreys-tili-A5-Page157.jpg',
    'https://i.ibb.co/BHJvFtN/Mel-Book-Koreys-tili-A5-Page158.jpg',
    'https://i.ibb.co/gz9w77v/Mel-Book-Koreys-tili-A5-Page159.jpg',
    'https://i.ibb.co/DY2nVFf/Mel-Book-Koreys-tili-A5-Page160.jpg',
    'https://i.ibb.co/cgL4qD3/Mel-Book-Koreys-tili-A5-Page161.jpg',
    'https://i.ibb.co/6gH2wpx/Mel-Book-Koreys-tili-A5-Page162.jpg',
    'https://i.ibb.co/K7PgVbn/Mel-Book-Koreys-tili-A5-Page163.jpg',
    'https://i.ibb.co/JCZz8nP/Mel-Book-Koreys-tili-A5-Page164.jpg',
    'https://i.ibb.co/4SHMdyy/Mel-Book-Koreys-tili-A5-Page165.jpg',
    'https://i.ibb.co/MVN23s4/Mel-Book-Koreys-tili-A5-Page166.jpg',
    'https://i.ibb.co/HGsZr03/Mel-Book-Koreys-tili-A5-Page167.jpg',
    'https://i.ibb.co/1J8TxPS/Mel-Book-Koreys-tili-A5-Page168.jpg',
    'https://i.ibb.co/2YxrjhN/Mel-Book-Koreys-tili-A5-Page169.jpg',
    'https://i.ibb.co/4MwRtS5/Mel-Book-Koreys-tili-A5-Page170.jpg',
    'https://i.ibb.co/6Y6bm68/Mel-Book-Koreys-tili-A5-Page171.jpg',
    'https://i.ibb.co/R40Z3Tr/Mel-Book-Koreys-tili-A5-Page172.jpg',
    'https://i.ibb.co/7WgXhWM/Mel-Book-Koreys-tili-A5-Page173.jpg',
    'https://i.ibb.co/V9Dnf1P/Mel-Book-Koreys-tili-A5-Page174.jpg',
    'https://i.ibb.co/vBRJG3M/Mel-Book-Koreys-tili-A5-Page175.jpg',
    'https://i.ibb.co/Tr1X8f8/Mel-Book-Koreys-tili-A5-Page176.jpg',
    'https://i.ibb.co/DL2HWg7/Mel-Book-Koreys-tili-A5-Page177.jpg',
    'https://i.ibb.co/vwrpVXv/Mel-Book-Koreys-tili-A5-Page178.jpg',
    'https://i.ibb.co/6g91912/Mel-Book-Koreys-tili-A5-Page179.jpg',
    'https://i.ibb.co/8XF2McL/Mel-Book-Koreys-tili-A5-Page180.jpg',
    'https://i.ibb.co/wcC1m7p/Mel-Book-Koreys-tili-A5-Page181.jpg',
    'https://i.ibb.co/2yptykT/Mel-Book-Koreys-tili-A5-Page182.jpg',
    'https://i.ibb.co/0mW4bkS/Mel-Book-Koreys-tili-A5-Page183.jpg',
    'https://i.ibb.co/WGXB1KD/Mel-Book-Koreys-tili-A5-Page184.jpg',
    'https://i.ibb.co/nC98kz7/Mel-Book-Koreys-tili-A5-Page185.jpg',
    'https://i.ibb.co/6ryBVtY/Mel-Book-Koreys-tili-A5-Page186.jpg',
    'https://i.ibb.co/yFwGq5D/Mel-Book-Koreys-tili-A5-Page187.jpg',
    'https://i.ibb.co/pPwwj8g/Mel-Book-Koreys-tili-A5-Page188.jpg',
    'https://i.ibb.co/6HhvkFp/Mel-Book-Koreys-tili-A5-Page189.jpg',
    'https://i.ibb.co/Yphn7Lq/Mel-Book-Koreys-tili-A5-Page190.jpg',
    'https://i.ibb.co/g6xBWZ6/Mel-Book-Koreys-tili-A5-Page191.jpg',
    'https://i.ibb.co/wCp7dRN/Mel-Book-Koreys-tili-A5-Page192.jpg',
    'https://i.ibb.co/kMqX6k9/Mel-Book-Koreys-tili-A5-Page193.jpg',
    'https://i.ibb.co/pQzsVRp/Mel-Book-Koreys-tili-A5-Page194.jpg',
    'https://i.ibb.co/PQYBFK1/Mel-Book-Koreys-tili-A5-Page195.jpg',
    'https://i.ibb.co/vcpGmYh/Mel-Book-Koreys-tili-A5-Page196.jpg',
    'https://i.ibb.co/yffXpYX/Mel-Book-Koreys-tili-A5-Page197.jpg',
    'https://i.ibb.co/JkwpGfK/Mel-Book-Koreys-tili-A5-Page198.jpg',
    'https://i.ibb.co/LhW0P72/Mel-Book-Koreys-tili-A5-Page199.jpg',
    'https://i.ibb.co/B3N9fyx/Mel-Book-Koreys-tili-A5-Page200.jpg',
    'https://i.ibb.co/WssWwk7/Mel-Book-Koreys-tili-A5-Page201.jpg',
    'https://i.ibb.co/DrGKywy/Mel-Book-Koreys-tili-A5-Page202.jpg',
    'https://i.ibb.co/mhpqY3w/Mel-Book-Koreys-tili-A5-Page203.jpg',
    'https://i.ibb.co/g91pcMM/Mel-Book-Koreys-tili-A5-Page204.jpg',
    'https://i.ibb.co/LQ7McL6/Mel-Book-Koreys-tili-A5-Page205.jpg',
    'https://i.ibb.co/pdc8WBB/Mel-Book-Koreys-tili-A5-Page206.jpg',
    'https://i.ibb.co/NjJGQNn/Mel-Book-Koreys-tili-A5-Page207.jpg',
    'https://i.ibb.co/VTmYqxR/Mel-Book-Koreys-tili-A5-Page208.jpg',
    'https://i.ibb.co/vZm6bCr/Mel-Book-Koreys-tili-A5-Page209.jpg',
    'https://i.ibb.co/z4fF2ZZ/Mel-Book-Koreys-tili-A5-Page210.jpg',
    'https://i.ibb.co/dLQKNJX/Mel-Book-Koreys-tili-A5-Page211.jpg',
    'https://i.ibb.co/kynwRmN/Mel-Book-Koreys-tili-A5-Page212.jpg',
    'https://i.ibb.co/DWdCVbj/Mel-Book-Koreys-tili-A5-Page213.jpg',
    'https://i.ibb.co/PCc4tpJ/Mel-Book-Koreys-tili-A5-Page214.jpg',
    'https://i.ibb.co/n8PzpJx/Mel-Book-Koreys-tili-A5-Page215.jpg',
    'https://i.ibb.co/PWm60X2/Mel-Book-Koreys-tili-A5-Page216.jpg',
    'https://i.ibb.co/x150MQ2/Mel-Book-Koreys-tili-A5-Page217.jpg',
    'https://i.ibb.co/7n5vPgx/Mel-Book-Koreys-tili-A5-Page218.jpg',
    'https://i.ibb.co/HYPhtHV/Mel-Book-Koreys-tili-A5-Page219.jpg',
    'https://i.ibb.co/1LxbLKB/Mel-Book-Koreys-tili-A5-Page220.jpg',
    'https://i.ibb.co/z485814/Mel-Book-Koreys-tili-A5-Page221.jpg',
    'https://i.ibb.co/mv9YML3/Mel-Book-Koreys-tili-A5-Page222.jpg',
    'https://i.ibb.co/kKTDRR5/Mel-Book-Koreys-tili-A5-Page223.jpg',
    'https://i.ibb.co/80qv4ZK/Mel-Book-Koreys-tili-A5-Page224.jpg',
    'https://i.ibb.co/YQLzc7N/Mel-Book-Koreys-tili-A5-Page225.jpg',
    'https://i.ibb.co/8g2Q0n9/Mel-Book-Koreys-tili-A5-Page226.jpg',
    'https://i.ibb.co/DkHJd2n/Mel-Book-Koreys-tili-A5-Page227.jpg',
    'https://i.ibb.co/m8z5dY3/Mel-Book-Koreys-tili-A5-Page228.jpg',
    'https://i.ibb.co/Z6s63T5/Mel-Book-Koreys-tili-A5-Page229.jpg',
    'https://i.ibb.co/r5MMqSP/Mel-Book-Koreys-tili-A5-Page230.jpg',
    'https://i.ibb.co/RYrnbcD/Mel-Book-Koreys-tili-A5-Page231.jpg',
    'https://i.ibb.co/HFTcj3V/Mel-Book-Koreys-tili-A5-Page232.jpg',
    'https://i.ibb.co/tctd3Yz/Mel-Book-Koreys-tili-A5-Page233.jpg',
    'https://i.ibb.co/z5TXcM0/Mel-Book-Koreys-tili-A5-Page234.jpg',
    'https://i.ibb.co/dj4NL7t/Mel-Book-Koreys-tili-A5-Page235.jpg',
    'https://i.ibb.co/XF2W8z2/Mel-Book-Koreys-tili-A5-Page236.jpg',
    'https://i.ibb.co/r5y2QdM/Mel-Book-Koreys-tili-A5-Page237.jpg',
    'https://i.ibb.co/S5HyNWC/Mel-Book-Koreys-tili-A5-Page238.jpg',
    'https://i.ibb.co/Qp0pBCD/Mel-Book-Koreys-tili-A5-Page239.jpg',
    'https://i.ibb.co/yQKXJfG/Mel-Book-Koreys-tili-A5-Page240.jpg',
    'https://i.ibb.co/vVxL6L0/Mel-Book-Koreys-tili-A5-Page241.jpg',
    'https://i.ibb.co/FYvtfXn/Mel-Book-Koreys-tili-A5-Page242.jpg',
    'https://i.ibb.co/tKdySC1/Mel-Book-Koreys-tili-A5-Page243.jpg',
    'https://i.ibb.co/B4bRwyL/Mel-Book-Koreys-tili-A5-Page244.jpg',
    'https://i.ibb.co/5KScSZF/Mel-Book-Koreys-tili-A5-Page245.jpg',
    'https://i.ibb.co/hL6qtPk/Mel-Book-Koreys-tili-A5-Page246.jpg',
    'https://i.ibb.co/Pc92Ls0/Mel-Book-Koreys-tili-A5-Page247.jpg',
    'https://i.ibb.co/WGq4b9c/Mel-Book-Koreys-tili-A5-Page248.jpg',
    'https://i.ibb.co/px6V0KL/Mel-Book-Koreys-tili-A5-Page249.jpg',
    'https://i.ibb.co/Qp3Bx5N/Mel-Book-Koreys-tili-A5-Page250.jpg',
    'https://i.ibb.co/rcNQBHM/Mel-Book-Koreys-tili-A5-Page252.jpg',
    'https://i.ibb.co/Pr1HL4k/Mel-Book-Koreys-tili-A5-Page251.jpg',
    'https://i.ibb.co/JH3F67y/Mel-Book-Koreys-tili-A5-Page253.jpg',
    'https://i.ibb.co/2t2BvG9/Mel-Book-Koreys-tili-A5-Page254.jpg',
    'https://i.ibb.co/WVxzpzJ/Mel-Book-Koreys-tili-A5-Page255.jpg',
    'https://i.ibb.co/bPMbpY9/Mel-Book-Koreys-tili-A5-Page256.jpg',
    'https://i.ibb.co/rscbkjG/Mel-Book-Koreys-tili-A5-Page257.jpg',
    'https://i.ibb.co/FgktcqV/Mel-Book-Koreys-tili-A5-Page258.jpg',
    'https://i.ibb.co/g6tvhvh/Mel-Book-Koreys-tili-A5-Page259.jpg',
    'https://i.ibb.co/gJtKwz5/Mel-Book-Koreys-tili-A5-Page260.jpg',
    'https://i.ibb.co/FsWy7qQ/Mel-Book-Koreys-tili-A5-Page261.jpg',
    'https://i.ibb.co/PGKv99N/Mel-Book-Koreys-tili-A5-Page263.jpg',
    'https://i.ibb.co/0GdjdC9/Mel-Book-Koreys-tili-A5-Page262.jpg',
    'https://i.ibb.co/jvzhhBN/Mel-Book-Koreys-tili-A5-Page264.jpg',
    'https://i.ibb.co/8dh6LVf/Mel-Book-Koreys-tili-A5-Page265.jpg',
    'https://i.ibb.co/1KDdvJJ/Mel-Book-Koreys-tili-A5-Page266.jpg',
    'https://i.ibb.co/VY6q4tN/Mel-Book-Koreys-tili-A5-Page267.jpg',
    'https://i.ibb.co/7b2f1Fs/Mel-Book-Koreys-tili-A5-Page268.jpg',
    'https://i.ibb.co/pntx6Q3/Mel-Book-Koreys-tili-A5-Page269.jpg',
    'https://i.ibb.co/5r0hs43/Mel-Book-Koreys-tili-A5-Page270.jpg',
    'https://i.ibb.co/r3j2ffq/Mel-Book-Koreys-tili-A5-Page271.jpg',
    'https://i.ibb.co/c6nphz2/Mel-Book-Koreys-tili-A5-Page272.jpg',
    'https://i.ibb.co/zxCSKNP/Mel-Book-Koreys-tili-A5-Page273.jpg',
    'https://i.ibb.co/L0bMkq6/Mel-Book-Koreys-tili-A5-Page274.jpg',
    'https://i.ibb.co/y674Nzj/Mel-Book-Koreys-tili-A5-Page275.jpg',
    'https://i.ibb.co/x3qxBnh/Mel-Book-Koreys-tili-A5-Page276.jpg',
    'https://i.ibb.co/98sJkqg/Mel-Book-Koreys-tili-A5-Page277.jpg',
    'https://i.ibb.co/1zZ0tzm/Mel-Book-Koreys-tili-A5-Page278.jpg',
    'https://i.ibb.co/chVqQgB/Mel-Book-Koreys-tili-A5-Page279.jpg',
    'https://i.ibb.co/zJK65D9/Mel-Book-Koreys-tili-A5-Page280.jpg',
    'https://i.ibb.co/0B2D7RK/Mel-Book-Koreys-tili-A5-Page281.jpg',
    'https://i.ibb.co/TYcY10z/Mel-Book-Koreys-tili-A5-Page282.jpg',
    'https://i.ibb.co/BcXC6sJ/Mel-Book-Koreys-tili-A5-Page283.jpg',
    'https://i.ibb.co/vZJcz4M/Mel-Book-Koreys-tili-A5-Page284.jpg',
    'https://i.ibb.co/CH20Bt9/Mel-Book-Koreys-tili-A5-Page285.jpg',
    'https://i.ibb.co/sgz5Qj6/Mel-Book-Koreys-tili-A5-Page286.jpg',
    'https://i.ibb.co/5TwQQbp/Mel-Book-Koreys-tili-A5-Page287.jpg',
    'https://i.ibb.co/1Rv8WVq/Mel-Book-Koreys-tili-A5-Page288.jpg',
    'https://i.ibb.co/KL86N2S/Mel-Book-Koreys-tili-A5-Page289.jpg',
    'https://i.ibb.co/3rFYDfh/Mel-Book-Koreys-tili-A5-Page290.jpg',
    'https://i.ibb.co/n8MMJHB/Mel-Book-Koreys-tili-A5-Page291.jpg',
    'https://i.ibb.co/G5mcvP7/Mel-Book-Koreys-tili-A5-Page292.jpg',
    'https://i.ibb.co/q7hgPJL/Mel-Book-Koreys-tili-A5-Page293.jpg',
    'https://i.ibb.co/PGd6vk2/Mel-Book-Koreys-tili-A5-Page294.jpg',
    'https://i.ibb.co/h2S7Bqt/Mel-Book-Koreys-tili-A5-Page295.jpg',
    'https://i.ibb.co/b7pFjPX/Mel-Book-Koreys-tili-A5-Page296.jpg',
    'https://i.ibb.co/1RzBQ0c/Mel-Book-Koreys-tili-A5-Page297.jpg',
    'https://i.ibb.co/YWHfXdH/Mel-Book-Koreys-tili-A5-Page298.jpg',
    'https://i.ibb.co/wrZbgZ5/Mel-Book-Koreys-tili-A5-Page299.jpg',
    'https://i.ibb.co/Bw3D1VS/Mel-Book-Koreys-tili-A5-Page300.jpg',
    'https://i.ibb.co/KytsbqQ/Mel-Book-Koreys-tili-A5-Page301.jpg',
    'https://i.ibb.co/KyxfdFB/Mel-Book-Koreys-tili-A5-Page302.jpg',
    'https://i.ibb.co/LpbHJb0/Mel-Book-Koreys-tili-A5-Page303.jpg',
    'https://i.ibb.co/qgYvFbH/Mel-Book-Koreys-tili-A5-Page304.jpg',
    'https://i.ibb.co/WyP4Cwc/Mel-Book-Koreys-tili-A5-Page305.jpg',
    'https://i.ibb.co/8s0c3Tn/Mel-Book-Koreys-tili-A5-Page306.jpg',
    'https://i.ibb.co/fQ2FnpQ/Mel-Book-Koreys-tili-A5-Page307.jpg',
    'https://i.ibb.co/2ZbwWtR/Mel-Book-Koreys-tili-A5-Page308.jpg',
    'https://i.ibb.co/1Lw4t1B/Mel-Book-Koreys-tili-A5-Page309.jpg',
    'https://i.ibb.co/SvB3Qt0/Mel-Book-Koreys-tili-A5-Page310.jpg',
    'https://i.ibb.co/yWqRTRC/Mel-Book-Koreys-tili-A5-Page311.jpg',
    'https://i.ibb.co/bHvphqR/Mel-Book-Koreys-tili-A5-Page312.jpg',
  ];
  @override
  Widget build(BuildContext context) {
    ScreenUtil.init(
      context,
      designSize: Size(360, 690),
      minTextAdapt: true,
    );
    if (widget.page < 0 || widget.page >= images.length){
      return Scaffold(
        backgroundColor: Colors.white,
        body: SafeArea(
          child: Center(
            child: Text('rahmat'),
          ),
        ),
      );
    }
    return Scaffold(
      backgroundColor: Colors.white,
      body: SafeArea(
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              SizedBox(height: 32.h),
              Container(
                height: 1.sh - 140.h,
                width: 1.sw,
                child: CachedNetworkImage(
                  imageUrl: images[widget.page],
                  fit: BoxFit.cover,
                  placeholder: (context, url) => Center(child: CircularProgressIndicator()),
                  errorWidget: (context, url, error) => Center(child: Icon(Icons.error)),
                ),
              )
            ],
          ),
        ),
      ),
    );

  }
}