import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class RustiliReading extends StatefulWidget {
  final int page;
  const RustiliReading({super.key, required this.page});

  @override
  State<RustiliReading> createState() => _RustiliReadingState();
}

class _RustiliReadingState extends State<RustiliReading> {
  List<String> images = [
    'https://i.ibb.co/8PncG8k/Mel-Book-Rus-tili-A5-page-0001.jpg',
    'https://i.ibb.co/8PncG8k/Mel-Book-Rus-tili-A5-page-0002.jpg',
    'https://i.ibb.co/QnjcSFH/Mel-Book-Rus-tili-A5-page-0018.jpg',
    'https://i.ibb.co/KD8Pd8t/Mel-Book-Rus-tili-A5-page-0027.jpg',
    'https://i.ibb.co/nRzMn12/Mel-Book-Rus-tili-A5-page-0031.jpg',
    'https://i.ibb.co/8YPhGnC/Mel-Book-Rus-tili-A5-page-0049.jpg',
    'https://i.ibb.co/SK0KWvV/Mel-Book-Rus-tili-A5-page-0050.jpg',
    'https://i.ibb.co/HC7H0VN/Mel-Book-Rus-tili-A5-page-0055.jpg',
    'https://i.ibb.co/1rn4pV0/Mel-Book-Rus-tili-A5-page-0065.jpg',
    'https://i.ibb.co/4sf9XTN/Mel-Book-Rus-tili-A5-page-0066.jpg',
    'https://i.ibb.co/7X0m42y/Mel-Book-Rus-tili-A5-page-0069.jpg',
    'https://i.ibb.co/JzpFYhz/Mel-Book-Rus-tili-A5-page-0071.jpg',
    'https://i.ibb.co/4tKTqXn/Mel-Book-Rus-tili-A5-page-0072.jpg',
    'https://i.ibb.co/vhz6DN3/Mel-Book-Rus-tili-A5-page-0076.jpg',
    'https://i.ibb.co/4Wrthpd/Mel-Book-Rus-tili-A5-page-0082.jpg',
    'https://i.ibb.co/GWxxY1c/Mel-Book-Rus-tili-A5-page-0106.jpg',
    'https://i.ibb.co/8800Mx6/Mel-Book-Rus-tili-A5-page-0107.jpg',
    'https://i.ibb.co/D9ktBH2/Mel-Book-Rus-tili-A5-page-0114.jpg',
    'https://i.ibb.co/YQYKC6V/Mel-Book-Rus-tili-A5-page-0118.jpg',
    'https://i.ibb.co/SPz5myY/Mel-Book-Rus-tili-A5-page-0124.jpg',
    'https://i.ibb.co/2YTM5V0/Mel-Book-Rus-tili-A5-page-0129.jpg',
    'https://i.ibb.co/fkxjpGq/Mel-Book-Rus-tili-A5-page-0149.jpg',
    'https://i.ibb.co/LQZVMRR/Mel-Book-Rus-tili-A5-page-0151.jpg',
    'https://i.ibb.co/vPC8qj1/Mel-Book-Rus-tili-A5-page-0153.jpg',
    'https://i.ibb.co/7nhK53H/Mel-Book-Rus-tili-A5-page-0155.jpg',
    'https://i.ibb.co/TggB54P/Mel-Book-Rus-tili-A5-page-0173.jpg',
    'https://i.ibb.co/4Kr0BPp/Mel-Book-Rus-tili-A5-page-0174.jpg',
    'https://i.ibb.co/t3KXRNX/Mel-Book-Rus-tili-A5-page-0185.jpg',
    'https://i.ibb.co/tmJpKw0/Mel-Book-Rus-tili-A5-page-0194.jpg',
    'https://i.ibb.co/St2MQtp/Mel-Book-Rus-tili-A5-page-0198.jpg',
    'https://i.ibb.co/ph98pfx/Mel-Book-Rus-tili-A5-page-0199.jpg',
    'https://i.ibb.co/Jrqjz38/Mel-Book-Rus-tili-A5-page-0207.jpg',
    'https://i.ibb.co/KhWh21M/Mel-Book-Rus-tili-A5-page-0210.jpg',
    'https://i.ibb.co/YNYRbKD/Mel-Book-Rus-tili-A5-page-0211.jpg',
    'https://i.ibb.co/0Fg8BXk/Mel-Book-Rus-tili-A5-page-0225.jpg',
    'https://i.ibb.co/K9DZ8m8/Mel-Book-Rus-tili-A5-page-0231.jpg',
    'https://i.ibb.co/bXxzK9Y/Mel-Book-Rus-tili-A5-page-0235.jpg',
    'https://i.ibb.co/WfSjBXC/Mel-Book-Rus-tili-A5-page-0245.jpg',
    'https://i.ibb.co/1bg0hVJ/Mel-Book-Rus-tili-A5-page-0250.jpg',
    'https://i.ibb.co/bPh09GH/Mel-Book-Rus-tili-A5-page-0258.jpg',
    'https://i.ibb.co/Ldsjhph/Mel-Book-Rus-tili-A5-page-0264.jpg',
    'https://i.ibb.co/dKKLqqY/Mel-Book-Rus-tili-A5-page-0266.jpg',
    'https://i.ibb.co/j30svmx/Mel-Book-Rus-tili-A5-page-0272.jpg',
    'https://i.ibb.co/sswZW7g/Mel-Book-Rus-tili-A5-page-0273.jpg',
    'https://i.ibb.co/Kyc5rq7/Mel-Book-Rus-tili-A5-page-0276.jpg',
    'https://i.ibb.co/FYddVfB/Mel-Book-Rus-tili-A5-page-0278.jpg',
    'https://i.ibb.co/WpWSJqj/Mel-Book-Rus-tili-A5-page-0288.jpg',
    'https://i.ibb.co/PD0KTLC/Mel-Book-Rus-tili-A5-page-0004.jpg',
    'https://i.ibb.co/r0MvJjx/Mel-Book-Rus-tili-A5-page-0005.jpg',
    'https://i.ibb.co/31WrQmQ/Mel-Book-Rus-tili-A5-page-0020.jpg',
    'https://i.ibb.co/n3Qkk6z/Mel-Book-Rus-tili-A5-page-0032.jpg',
    'https://i.ibb.co/HPQgvHN/Mel-Book-Rus-tili-A5-page-0033.jpg',
    'https://i.ibb.co/cD2T9fv/Mel-Book-Rus-tili-A5-page-0040.jpg',
    'https://i.ibb.co/gRCwW5P/Mel-Book-Rus-tili-A5-page-0051.jpg',
    'https://i.ibb.co/Zd9zXFh/Mel-Book-Rus-tili-A5-page-0054.jpg',
    'https://i.ibb.co/6XgGK8S/Mel-Book-Rus-tili-A5-page-0056.jpg',
    'https://i.ibb.co/ZzJTNj6/Mel-Book-Rus-tili-A5-page-0063.jpg',
    'https://i.ibb.co/sC1rhWZ/Mel-Book-Rus-tili-A5-page-0064.jpg',
    'https://i.ibb.co/ysktBNW/Mel-Book-Rus-tili-A5-page-0075.jpg',
    'https://i.ibb.co/hL4LcRL/Mel-Book-Rus-tili-A5-page-0085.jpg',
    'https://i.ibb.co/b7ZGtL0/Mel-Book-Rus-tili-A5-page-0088.jpg',
    'https://i.ibb.co/NyRgHvt/Mel-Book-Rus-tili-A5-page-0093.jpg',
    'https://i.ibb.co/X8b4jg6/Mel-Book-Rus-tili-A5-page-0095.jpg',
    'https://i.ibb.co/bsk00nP/Mel-Book-Rus-tili-A5-page-0096.jpg',
    'https://i.ibb.co/zrsvRmM/Mel-Book-Rus-tili-A5-page-0104.jpg',
    'https://i.ibb.co/9tMdYpV/Mel-Book-Rus-tili-A5-page-0105.jpg',
    'https://i.ibb.co/T1dqHfC/Mel-Book-Rus-tili-A5-page-0108.jpg',
    'https://i.ibb.co/8YkDVX3/Mel-Book-Rus-tili-A5-page-0111.jpg',
    'https://i.ibb.co/BCn7FPV/Mel-Book-Rus-tili-A5-page-0125.jpg',
    'https://i.ibb.co/qxnjWYP/Mel-Book-Rus-tili-A5-page-0126.jpg',
    'https://i.ibb.co/VLYVW9Y/Mel-Book-Rus-tili-A5-page-0127.jpg',
    'https://i.ibb.co/h26Q7xv/Mel-Book-Rus-tili-A5-page-0131.jpg',
    'https://i.ibb.co/5vnWcW4/Mel-Book-Rus-tili-A5-page-0157.jpg',
    'https://i.ibb.co/Qkv9dgK/Mel-Book-Rus-tili-A5-page-0159.jpg',
    'https://i.ibb.co/B2kzrMs/Mel-Book-Rus-tili-A5-page-0160.jpg',
    'https://i.ibb.co/fF7c0Lg/Mel-Book-Rus-tili-A5-page-0165.jpg',
    'https://i.ibb.co/zFd3RK9/Mel-Book-Rus-tili-A5-page-0166.jpg',
    'https://i.ibb.co/pPXp44w/Mel-Book-Rus-tili-A5-page-0171.jpg',
    'https://i.ibb.co/q7StkBS/Mel-Book-Rus-tili-A5-page-0177.jpg',
    'https://i.ibb.co/3Td4tPW/Mel-Book-Rus-tili-A5-page-0180.jpg',
    'https://i.ibb.co/z5DXYG3/Mel-Book-Rus-tili-A5-page-0181.jpg',
    'https://i.ibb.co/WczwyYc/Mel-Book-Rus-tili-A5-page-0190.jpg',
    'https://i.ibb.co/bQtbmfv/Mel-Book-Rus-tili-A5-page-0201.jpg',
    'https://i.ibb.co/tZLw5bK/Mel-Book-Rus-tili-A5-page-0209.jpg',
    'https://i.ibb.co/hgjJ2PP/Mel-Book-Rus-tili-A5-page-0223.jpg',
    'https://i.ibb.co/kcp0V4s/Mel-Book-Rus-tili-A5-page-0227.jpg',
    'https://i.ibb.co/rc6pv8k/Mel-Book-Rus-tili-A5-page-0259.jpg',
    'https://i.ibb.co/6XYtJRW/Mel-Book-Rus-tili-A5-page-0261.jpg',
    'https://i.ibb.co/jyb34vs/Mel-Book-Rus-tili-A5-page-0263.jpg',
    'https://i.ibb.co/RbSWpY7/Mel-Book-Rus-tili-A5-page-0268.jpg',
    'https://i.ibb.co/MPGcF1F/Mel-Book-Rus-tili-A5-page-0275.jpg',
    'https://i.ibb.co/BqpwCyP/Mel-Book-Rus-tili-A5-page-0282.jpg',
    'https://i.ibb.co/HBDgpq5/Mel-Book-Rus-tili-A5-page-0290.jpg',
    'https://i.ibb.co/ZShVFN3/Mel-Book-Rus-tili-A5-page-0295.jpg',
    'https://i.ibb.co/9rXQ9YT/Mel-Book-Rus-tili-A5-page-0009.jpg',
    'https://i.ibb.co/ng8YvCb/Mel-Book-Rus-tili-A5-page-0013.jpg',
    'https://i.ibb.co/PQCw81d/Mel-Book-Rus-tili-A5-page-0024.jpg',
    'https://i.ibb.co/fQKTLnh/Mel-Book-Rus-tili-A5-page-0036.jpg',
    'https://i.ibb.co/sPTM6ww/Mel-Book-Rus-tili-A5-page-0043.jpg',
    'https://i.ibb.co/XJYXgy2/Mel-Book-Rus-tili-A5-page-0044.jpg',
    'https://i.ibb.co/1GphTMz/Mel-Book-Rus-tili-A5-page-0060.jpg',
    'https://i.ibb.co/wNRM5WS/Mel-Book-Rus-tili-A5-page-0062.jpg',
    'https://i.ibb.co/Nn9cRqn/Mel-Book-Rus-tili-A5-page-0074.jpg',
    'https://i.ibb.co/pwD7V7v/Mel-Book-Rus-tili-A5-page-0084.jpg',
    'https://i.ibb.co/6PG9f57/Mel-Book-Rus-tili-A5-page-0099.jpg',
    'https://i.ibb.co/s5cNNWJ/Mel-Book-Rus-tili-A5-page-0100.jpg',
    'https://i.ibb.co/6vJSGtS/Mel-Book-Rus-tili-A5-page-0103.jpg',
    'https://i.ibb.co/Yhcxnkn/Mel-Book-Rus-tili-A5-page-0120.jpg',
    'https://i.ibb.co/Rz0rKHC/Mel-Book-Rus-tili-A5-page-0135.jpg',
    'https://i.ibb.co/qn354C5/Mel-Book-Rus-tili-A5-page-0138.jpg',
    'https://i.ibb.co/cb1JfD3/Mel-Book-Rus-tili-A5-page-0141.jpg',
    'https://i.ibb.co/6XK7QS0/Mel-Book-Rus-tili-A5-page-0142.jpg',
    'https://i.ibb.co/TYcNbrh/Mel-Book-Rus-tili-A5-page-0147.jpg',
    'https://i.ibb.co/cxMw1VZ/Mel-Book-Rus-tili-A5-page-0150.jpg',
    'https://i.ibb.co/GszL5xY/Mel-Book-Rus-tili-A5-page-0161.jpg',
    'https://i.ibb.co/H4D9PHC/Mel-Book-Rus-tili-A5-page-0162.jpg',
    'https://i.ibb.co/ZfJxTtj/Mel-Book-Rus-tili-A5-page-0182.jpg',
    'https://i.ibb.co/dQMCNcG/Mel-Book-Rus-tili-A5-page-0183.jpg',
    'https://i.ibb.co/T2VZZgx/Mel-Book-Rus-tili-A5-page-0186.jpg',
    'https://i.ibb.co/zGvcBPt/Mel-Book-Rus-tili-A5-page-0203.jpg',
    'https://i.ibb.co/q56441H/Mel-Book-Rus-tili-A5-page-0204.jpg',
    'https://i.ibb.co/JKsH4vJ/Mel-Book-Rus-tili-A5-page-0206.jpg',
    'https://i.ibb.co/fvfx4rY/Mel-Book-Rus-tili-A5-page-0213.jpg',
    'https://i.ibb.co/S0Ffvjw/Mel-Book-Rus-tili-A5-page-0215.jpg',
    'https://i.ibb.co/vc3NrVb/Mel-Book-Rus-tili-A5-page-0224.jpg',
    'https://i.ibb.co/nL8w3k9/Mel-Book-Rus-tili-A5-page-0228.jpg',
    'https://i.ibb.co/LN7xfXz/Mel-Book-Rus-tili-A5-page-0229.jpg',
    'https://i.ibb.co/pffqP20/Mel-Book-Rus-tili-A5-page-0238.jpg',
    'https://i.ibb.co/rZkzyjf/Mel-Book-Rus-tili-A5-page-0242.jpg',
    'https://i.ibb.co/J540CmW/Mel-Book-Rus-tili-A5-page-0244.jpg',
    'https://i.ibb.co/JvRBMkK/Mel-Book-Rus-tili-A5-page-0248.jpg',
    'https://i.ibb.co/cQmM2zZ/Mel-Book-Rus-tili-A5-page-0255.jpg',
    'https://i.ibb.co/KxHfXs9/Mel-Book-Rus-tili-A5-page-0256.jpg',
    'https://i.ibb.co/7k7mm9r/Mel-Book-Rus-tili-A5-page-0265.jpg',
    'https://i.ibb.co/hs7jHKz/Mel-Book-Rus-tili-A5-page-0269.jpg',
    'https://i.ibb.co/MNnMCpP/Mel-Book-Rus-tili-A5-page-0280.jpg',
    'https://i.ibb.co/wLdZYBP/Mel-Book-Rus-tili-A5-page-0281.jpg',
    'https://i.ibb.co/MVbGFrt/Mel-Book-Rus-tili-A5-page-0291.jpg',
    'https://i.ibb.co/gPJ1w4c/Mel-Book-Rus-tili-A5-page-0294.jpg',
    'https://i.ibb.co/f2M46Jf/Mel-Book-Rus-tili-A5-page-0296.jpg',
    'https://i.ibb.co/19qgC8M/Mel-Book-Rus-tili-A5-page-0012.jpg',
    'https://i.ibb.co/YZRrQp1/Mel-Book-Rus-tili-A5-page-0014.jpg',
    'https://i.ibb.co/wCqf0wS/Mel-Book-Rus-tili-A5-page-0015.jpg',
    'https://i.ibb.co/xL61b7x/Mel-Book-Rus-tili-A5-page-0019.jpg',
    'https://i.ibb.co/jJZL2zz/Mel-Book-Rus-tili-A5-page-0021.jpg',
    'https://i.ibb.co/RDQZxq7/Mel-Book-Rus-tili-A5-page-0038.jpg',
    'https://i.ibb.co/ynXbSrJ/Mel-Book-Rus-tili-A5-page-0052.jpg',
    'https://i.ibb.co/xF3dmSZ/Mel-Book-Rus-tili-A5-page-0061.jpg',
    'https://i.ibb.co/LQXFSfn/Mel-Book-Rus-tili-A5-page-0070.jpg',
    'https://i.ibb.co/swkk8sj/Mel-Book-Rus-tili-A5-page-0073.jpg',
    'https://i.ibb.co/S6RLvfJ/Mel-Book-Rus-tili-A5-page-0077.jpg',
    'https://i.ibb.co/3hPZJfm/Mel-Book-Rus-tili-A5-page-0089.jpg',
    'https://i.ibb.co/v48D60c/Mel-Book-Rus-tili-A5-page-0090.jpg',
    'https://i.ibb.co/LNWD5YZ/Mel-Book-Rus-tili-A5-page-0098.jpg',
    'https://i.ibb.co/KW7X72n/Mel-Book-Rus-tili-A5-page-0101.jpg',
    'https://i.ibb.co/HF9hZr9/Mel-Book-Rus-tili-A5-page-0102.jpg',
    'https://i.ibb.co/j5stGTH/Mel-Book-Rus-tili-A5-page-0113.jpg',
    'https://i.ibb.co/RSmWBvQ/Mel-Book-Rus-tili-A5-page-0122.jpg',
    'https://i.ibb.co/DLJvSP8/Mel-Book-Rus-tili-A5-page-0130.jpg',
    'https://i.ibb.co/2drn8dg/Mel-Book-Rus-tili-A5-page-0134.jpg',
    'https://i.ibb.co/mRYHk2C/Mel-Book-Rus-tili-A5-page-0137.jpg',
    'https://i.ibb.co/1MPdVvv/Mel-Book-Rus-tili-A5-page-0139.jpg',
    'https://i.ibb.co/fFdYJfs/Mel-Book-Rus-tili-A5-page-0152.jpg',
    'https://i.ibb.co/VVpdRcQ/Mel-Book-Rus-tili-A5-page-0156.jpg',
    'https://i.ibb.co/TPmKpQV/Mel-Book-Rus-tili-A5-page-0158.jpg',
    'https://i.ibb.co/jGpHdBV/Mel-Book-Rus-tili-A5-page-0169.jpg',
    'https://i.ibb.co/F7WSMCk/Mel-Book-Rus-tili-A5-page-0179.jpg',
    'https://i.ibb.co/ZghcRbH/Mel-Book-Rus-tili-A5-page-0184.jpg',
    'https://i.ibb.co/cFP09sf/Mel-Book-Rus-tili-A5-page-0187.jpg',
    'https://i.ibb.co/tHJVhgW/Mel-Book-Rus-tili-A5-page-0191.jpg',
    'https://i.ibb.co/BPvjzDf/Mel-Book-Rus-tili-A5-page-0193.jpg',
    'https://i.ibb.co/xqKx7qN/Mel-Book-Rus-tili-A5-page-0200.jpg',
    'https://i.ibb.co/ZBfgCPb/Mel-Book-Rus-tili-A5-page-0205.jpg',
    'https://i.ibb.co/JBC4SW3/Mel-Book-Rus-tili-A5-page-0214.jpg',
    'https://i.ibb.co/J26yt4j/Mel-Book-Rus-tili-A5-page-0217.jpg',
    'https://i.ibb.co/rvsbnBM/Mel-Book-Rus-tili-A5-page-0221.jpg',
    'https://i.ibb.co/C1bR775/Mel-Book-Rus-tili-A5-page-0236.jpg',
    'https://i.ibb.co/SnYKDv4/Mel-Book-Rus-tili-A5-page-0239.jpg',
    'https://i.ibb.co/Msy9HmY/Mel-Book-Rus-tili-A5-page-0274.jpg',
    'https://i.ibb.co/2YJP7P4/Mel-Book-Rus-tili-A5-page-0279.jpg',
    'https://i.ibb.co/L5ft5Cb/Mel-Book-Rus-tili-A5-page-0283.jpg',
    'https://i.ibb.co/qkKyNMz/Mel-Book-Rus-tili-A5-page-0284.jpg',
    'https://i.ibb.co/y4Qp9Hb/Mel-Book-Rus-tili-A5-page-0292.jpg',
    'https://i.ibb.co/ZfGprGg/Mel-Book-Rus-tili-A5-page-0293.jpg',
    'https://i.ibb.co/Y0VjDXh/Mel-Book-Rus-tili-A5-page-0007.jpg',
    'https://i.ibb.co/Y7mRgSR/Mel-Book-Rus-tili-A5-page-0017.jpg',
    'https://i.ibb.co/3phFBf2/Mel-Book-Rus-tili-A5-page-0023.jpg',
    'https://i.ibb.co/VSDWV2Z/Mel-Book-Rus-tili-A5-page-0034.jpg',
    'https://i.ibb.co/CzVQCcP/Mel-Book-Rus-tili-A5-page-0035.jpg',
    'https://i.ibb.co/kGgNFs3/Mel-Book-Rus-tili-A5-page-0042.jpg',
    'https://i.ibb.co/r2G4453/Mel-Book-Rus-tili-A5-page-0045.jpg',
    'https://i.ibb.co/nBshrCn/Mel-Book-Rus-tili-A5-page-0047.jpg',
    'https://i.ibb.co/XkJLwPD/Mel-Book-Rus-tili-A5-page-0048.jpg',
    'https://i.ibb.co/LrhZRh4/Mel-Book-Rus-tili-A5-page-0057.jpg',
    'https://i.ibb.co/QKRYzRg/Mel-Book-Rus-tili-A5-page-0059.jpg',
    'https://i.ibb.co/VSFGWW8/Mel-Book-Rus-tili-A5-page-0078.jpg',
    'https://i.ibb.co/L0CDf33/Mel-Book-Rus-tili-A5-page-0079.jpg',
    'https://i.ibb.co/2jfs5hC/Mel-Book-Rus-tili-A5-page-0081.jpg',
    'https://i.ibb.co/g4wjwqK/Mel-Book-Rus-tili-A5-page-0087.jpg',
    'https://i.ibb.co/6JVBtfh/Mel-Book-Rus-tili-A5-page-0109.jpg',
    'https://i.ibb.co/f1HwrtT/Mel-Book-Rus-tili-A5-page-0110.jpg',
    'https://i.ibb.co/2WVLDnH/Mel-Book-Rus-tili-A5-page-0115.jpg',
    'https://i.ibb.co/rkNCYdV/Mel-Book-Rus-tili-A5-page-0119.jpg',
    'https://i.ibb.co/m0zGRDc/Mel-Book-Rus-tili-A5-page-0121.jpg',
    'https://i.ibb.co/ccCpMpP/Mel-Book-Rus-tili-A5-page-0123.jpg',
    'https://i.ibb.co/XDjycV8/Mel-Book-Rus-tili-A5-page-0133.jpg',
    'https://i.ibb.co/TbcZTct/Mel-Book-Rus-tili-A5-page-0140.jpg',
    'https://i.ibb.co/bKkjPpG/Mel-Book-Rus-tili-A5-page-0143.jpg',
    'https://i.ibb.co/xMyHttH/Mel-Book-Rus-tili-A5-page-0145.jpg',
    'https://i.ibb.co/JpcRFyT/Mel-Book-Rus-tili-A5-page-0146.jpg',
    'https://i.ibb.co/VCqBtpT/Mel-Book-Rus-tili-A5-page-0148.jpg',
    'https://i.ibb.co/1qfr4pr/Mel-Book-Rus-tili-A5-page-0163.jpg',
    'https://i.ibb.co/BCCsx3F/Mel-Book-Rus-tili-A5-page-0175.jpg',
    'https://i.ibb.co/23BBzgj/Mel-Book-Rus-tili-A5-page-0188.jpg',
    'https://i.ibb.co/HdQw4zq/Mel-Book-Rus-tili-A5-page-0192.jpg',
    'https://i.ibb.co/vs8Tchg/Mel-Book-Rus-tili-A5-page-0196.jpg',
    'https://i.ibb.co/kq0X1J2/Mel-Book-Rus-tili-A5-page-0216.jpg',
    'https://i.ibb.co/nb9DvBj/Mel-Book-Rus-tili-A5-page-0219.jpg',
    'https://i.ibb.co/mNZ3VzW/Mel-Book-Rus-tili-A5-page-0226.jpg',
    'https://i.ibb.co/HtkQ4cp/Mel-Book-Rus-tili-A5-page-0233.jpg',
    'https://i.ibb.co/LYGV1Ww/Mel-Book-Rus-tili-A5-page-0234.jpg',
    'https://i.ibb.co/hBVKxjB/Mel-Book-Rus-tili-A5-page-0243.jpg',
    'https://i.ibb.co/JxHzQmz/Mel-Book-Rus-tili-A5-page-0246.jpg',
    'https://i.ibb.co/ThNrSYp/Mel-Book-Rus-tili-A5-page-0251.jpg',
    'https://i.ibb.co/526fMpQ/Mel-Book-Rus-tili-A5-page-0253.jpg',
    'https://i.ibb.co/kD9K3Wq/Mel-Book-Rus-tili-A5-page-0254.jpg',
    'https://i.ibb.co/dkR50Bc/Mel-Book-Rus-tili-A5-page-0260.jpg',
    'https://i.ibb.co/pj01X3X/Mel-Book-Rus-tili-A5-page-0271.jpg',
    'https://i.ibb.co/qxP3sty/Mel-Book-Rus-tili-A5-page-0285.jpg',
    'https://i.ibb.co/Cbrsb4B/Mel-Book-Rus-tili-A5-page-0001.jpg',
    'https://i.ibb.co/qRkMM2v/Mel-Book-Rus-tili-A5-page-0006.jpg',
    'https://i.ibb.co/947WZvH/Mel-Book-Rus-tili-A5-page-0011.jpg',
    'https://i.ibb.co/2P6f4GQ/Mel-Book-Rus-tili-A5-page-0016.jpg',
    'https://i.ibb.co/zSNfS4X/Mel-Book-Rus-tili-A5-page-0022.jpg',
    'https://i.ibb.co/QbDWX1T/Mel-Book-Rus-tili-A5-page-0025.jpg',
    'https://i.ibb.co/GcNTTkw/Mel-Book-Rus-tili-A5-page-0026.jpg',
    'https://i.ibb.co/8xnnqNq/Mel-Book-Rus-tili-A5-page-0041.jpg',
    'https://i.ibb.co/ThxYwdL/Mel-Book-Rus-tili-A5-page-0067.jpg',
    'https://i.ibb.co/v1LhbWK/Mel-Book-Rus-tili-A5-page-0068.jpg',
    'https://i.ibb.co/rwKG28B/Mel-Book-Rus-tili-A5-page-0080.jpg',
    'https://i.ibb.co/WpYhVqq/Mel-Book-Rus-tili-A5-page-0083.jpg',
    'https://i.ibb.co/VWP1PW4/Mel-Book-Rus-tili-A5-page-0086.jpg',
    'https://i.ibb.co/Wg3vbmC/Mel-Book-Rus-tili-A5-page-0094.jpg',
    'https://i.ibb.co/wQH5sCn/Mel-Book-Rus-tili-A5-page-0132.jpg',
    'https://i.ibb.co/X7994zJ/Mel-Book-Rus-tili-A5-page-0136.jpg',
    'https://i.ibb.co/vzZs2VD/Mel-Book-Rus-tili-A5-page-0144.jpg',
    'https://i.ibb.co/T12H2yb/Mel-Book-Rus-tili-A5-page-0154.jpg',
    'https://i.ibb.co/MV86f2J/Mel-Book-Rus-tili-A5-page-0164.jpg',
    'https://i.ibb.co/PxfT6b6/Mel-Book-Rus-tili-A5-page-0170.jpg',
    'https://i.ibb.co/X4QXqVT/Mel-Book-Rus-tili-A5-page-0172.jpg',
    'https://i.ibb.co/2qkQXKN/Mel-Book-Rus-tili-A5-page-0176.jpg',
    'https://i.ibb.co/xJF1fNs/Mel-Book-Rus-tili-A5-page-0178.jpg',
    'https://i.ibb.co/rMGmbS9/Mel-Book-Rus-tili-A5-page-0195.jpg',
    'https://i.ibb.co/y6Mmb1r/Mel-Book-Rus-tili-A5-page-0197.jpg',
    'https://i.ibb.co/Ht85r9p/Mel-Book-Rus-tili-A5-page-0202.jpg',
    'https://i.ibb.co/QPxQBnP/Mel-Book-Rus-tili-A5-page-0208.jpg',
    'https://i.ibb.co/WzMZwvn/Mel-Book-Rus-tili-A5-page-0218.jpg',
    'https://i.ibb.co/yR8xWHv/Mel-Book-Rus-tili-A5-page-0220.jpg',
    'https://i.ibb.co/7S2zBYR/Mel-Book-Rus-tili-A5-page-0222.jpg',
    'https://i.ibb.co/DkGkzPK/Mel-Book-Rus-tili-A5-page-0230.jpg',
    'https://i.ibb.co/MR4gmRf/Mel-Book-Rus-tili-A5-page-0232.jpg',
    'https://i.ibb.co/ZJBZ6mL/Mel-Book-Rus-tili-A5-page-0237.jpg',
    'https://i.ibb.co/WHVftYG/Mel-Book-Rus-tili-A5-page-0240.jpg',
    'https://i.ibb.co/ScprRFb/Mel-Book-Rus-tili-A5-page-0247.jpg',
    'https://i.ibb.co/Tt9zRxh/Mel-Book-Rus-tili-A5-page-0249.jpg',
    'https://i.ibb.co/sH5z6gm/Mel-Book-Rus-tili-A5-page-0257.jpg',
    'https://i.ibb.co/BgHJDj4/Mel-Book-Rus-tili-A5-page-0262.jpg',
    'https://i.ibb.co/tHcpMjb/Mel-Book-Rus-tili-A5-page-0267.jpg',
    'https://i.ibb.co/G9hJ6sN/Mel-Book-Rus-tili-A5-page-0270.jpg',
    'https://i.ibb.co/2dWwvZd/Mel-Book-Rus-tili-A5-page-0277.jpg',
    'https://i.ibb.co/xm1xZLf/Mel-Book-Rus-tili-A5-page-0287.jpg',
    'https://i.ibb.co/YdxVPN6/Mel-Book-Rus-tili-A5-page-0289.jpg',
    'https://i.ibb.co/3BdPRVK/Mel-Book-Rus-tili-A5-page-0003.jpg',
    'https://i.ibb.co/zx27dx2/Mel-Book-Rus-tili-A5-page-0008.jpg',
    'https://i.ibb.co/r5GWRTk/Mel-Book-Rus-tili-A5-page-0010.jpg',
    'https://i.ibb.co/YNJppMF/Mel-Book-Rus-tili-A5-page-0028.jpg',
    'https://i.ibb.co/T4BqC2L/Mel-Book-Rus-tili-A5-page-0029.jpg',
    'https://i.ibb.co/MS9cXf8/Mel-Book-Rus-tili-A5-page-0030.jpg',
    'https://i.ibb.co/YcWW45D/Mel-Book-Rus-tili-A5-page-0037.jpg',
    'https://i.ibb.co/b7kfTpk/Mel-Book-Rus-tili-A5-page-0039.jpg',
    'https://i.ibb.co/Y8cD0Dr/Mel-Book-Rus-tili-A5-page-0046.jpg',
    'https://i.ibb.co/jyM7Rxx/Mel-Book-Rus-tili-A5-page-0053.jpg',
    'https://i.ibb.co/fvQ1LdB/Mel-Book-Rus-tili-A5-page-0058.jpg',
    'https://i.ibb.co/4JNtmcL/Mel-Book-Rus-tili-A5-page-0091.jpg',
    'https://i.ibb.co/1QFrBkJ/Mel-Book-Rus-tili-A5-page-0092.jpg',
    'https://i.ibb.co/f2ZG1bm/Mel-Book-Rus-tili-A5-page-0097.jpg',
    'https://i.ibb.co/9YthJPG/Mel-Book-Rus-tili-A5-page-0112.jpg',
    'https://i.ibb.co/Qnw8FL2/Mel-Book-Rus-tili-A5-page-0116.jpg',
    'https://i.ibb.co/5nQHyjJ/Mel-Book-Rus-tili-A5-page-0117.jpg',
    'https://i.ibb.co/hHnjtTp/Mel-Book-Rus-tili-A5-page-0128.jpg',
    'https://i.ibb.co/gWkd4Db/Mel-Book-Rus-tili-A5-page-0167.jpg',
    'https://i.ibb.co/b5yt7GY/Mel-Book-Rus-tili-A5-page-0168.jpg',
    'https://i.ibb.co/k6JP3Zw/Mel-Book-Rus-tili-A5-page-0189.jpg',
    'https://i.ibb.co/7VwfB9R/Mel-Book-Rus-tili-A5-page-0212.jpg',
    'https://i.ibb.co/v3BqKQ6/Mel-Book-Rus-tili-A5-page-0241.jpg',
    'https://i.ibb.co/6RLCdkh/Mel-Book-Rus-tili-A5-page-0252.jpg',
    'https://i.ibb.co/4NRCvVh/Mel-Book-Rus-tili-A5-page-0286.jpg',
  ];
  @override
  Widget build(BuildContext context) {
    ScreenUtil.init(
      context,
      designSize: const Size(360, 690),
      minTextAdapt: true,
    );
    if (widget.page < 0 || widget.page >= images.length){
      return const Scaffold(
        backgroundColor: Colors.white,
        body: SafeArea(
          child: Center(
            child: Text('Veroq index tugadi'),
          ),
        ),
      );
    }
    return Scaffold(
      backgroundColor: Colors.white,
      body: SafeArea(
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              SizedBox(height: 32.h),
              SizedBox(
                height: 1.sh - 140.h,
                width: 1.sw,
                child: CachedNetworkImage(
                  imageUrl: images[widget.page],
                  fit: BoxFit.cover,
                  placeholder: (context, url) => const Center(child: CircularProgressIndicator()),
                  errorWidget: (context, url, error) => const Center(child: Icon(Icons.error)),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}