import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
class ArabTileReading extends StatefulWidget {
  final int page;
  const ArabTileReading({super.key, required this.page});

  @override
  State<ArabTileReading> createState() => _ArabTileReadingState();
}

class _ArabTileReadingState extends State<ArabTileReading> {
  List<String> images = [
    'https://i.ibb.co/4RT0MSW/Mel-Book-Arab-tili-A5-1-compressed-page-0001.jpg',
    'https://i.ibb.co/4RT0MSW/Mel-Book-Arab-tili-A5-1-compressed-page-0001.jpg',
    'https://i.ibb.co/d6yj3Qk/Mel-Book-Arab-tili-A5-1-compressed-page-0002.jpg',
    'https://i.ibb.co/GTpCGdK/Mel-Book-Arab-tili-A5-1-compressed-page-0003.jpg',
    'https://i.ibb.co/KGrv0cb/Mel-Book-Arab-tili-A5-1-compressed-page-0004.jpg',
    'https://i.ibb.co/tLk6rZH/Mel-Book-Arab-tili-A5-1-compressed-page-0005.jpg',
    'https://i.ibb.co/Tbrr9kM/Mel-Book-Arab-tili-A5-1-compressed-page-0006.jpg',
    'https://i.ibb.co/SvvmbMT/Mel-Book-Arab-tili-A5-1-compressed-page-0007.jpg',
    'https://i.ibb.co/fGk8BQj/Mel-Book-Arab-tili-A5-1-compressed-page-0008.jpg',
    'https://i.ibb.co/c2RS3bk/Mel-Book-Arab-tili-A5-1-compressed-page-0009.jpg',
    'https://i.ibb.co/1qgTxG4/Mel-Book-Arab-tili-A5-1-compressed-page-0010.jpg',
    'https://i.ibb.co/PGxPpjQ/Mel-Book-Arab-tili-A5-1-compressed-page-0011.jpg',
    'https://i.ibb.co/XJf2SJN/Mel-Book-Arab-tili-A5-1-compressed-page-0012.jpg',
    'https://i.ibb.co/JkTgV9M/Mel-Book-Arab-tili-A5-1-compressed-page-0013.jpg',
    'https://i.ibb.co/n7rHjJx/Mel-Book-Arab-tili-A5-1-compressed-page-0014.jpg',
    'https://i.ibb.co/fvvDcDY/Mel-Book-Arab-tili-A5-1-compressed-page-0015.jpg',
    'https://i.ibb.co/NjzWSgg/Mel-Book-Arab-tili-A5-1-compressed-page-0016.jpg',
    'https://i.ibb.co/BtdcYLh/Mel-Book-Arab-tili-A5-1-compressed-page-0017.jpg',
    'https://i.ibb.co/F3MYRKb/Mel-Book-Arab-tili-A5-1-compressed-page-0018.jpg',
    'https://i.ibb.co/bvrw4wt/Mel-Book-Arab-tili-A5-1-compressed-page-0019.jpg',
    'https://i.ibb.co/njYFZXc/Mel-Book-Arab-tili-A5-1-compressed-page-0020.jpg',
    'https://i.ibb.co/F8CjYgv/Mel-Book-Arab-tili-A5-1-compressed-page-0021.jpg',
    'https://i.ibb.co/92DrbVK/Mel-Book-Arab-tili-A5-1-compressed-page-0022.jpg',
    'https://i.ibb.co/MSk3zYf/Mel-Book-Arab-tili-A5-1-compressed-page-0023.jpg',
    'https://i.ibb.co/kByydqv/Mel-Book-Arab-tili-A5-1-compressed-page-0024.jpg',
    'https://i.ibb.co/8rfk9Ty/Mel-Book-Arab-tili-A5-1-compressed-page-0025.jpg',
    'https://i.ibb.co/BwX4xCx/Mel-Book-Arab-tili-A5-1-compressed-page-0026.jpg',
    'https://i.ibb.co/Zh0qc8H/Mel-Book-Arab-tili-A5-1-compressed-page-0027.jpg',
    'https://i.ibb.co/9h90FCS/Mel-Book-Arab-tili-A5-1-compressed-page-0028.jpg',
    'https://i.ibb.co/R6DCPqZ/Mel-Book-Arab-tili-A5-1-compressed-page-0029.jpg',
    'https://i.ibb.co/cXkkW5T/Mel-Book-Arab-tili-A5-1-compressed-page-0030.jpg',
    'https://i.ibb.co/n0ms0Qj/Mel-Book-Arab-tili-A5-1-compressed-page-0031.jpg',
    'https://i.ibb.co/vkS2rMn/Mel-Book-Arab-tili-A5-1-compressed-page-0032.jpg',
    'https://i.ibb.co/ct651fb/Mel-Book-Arab-tili-A5-1-compressed-page-0033.jpg',
    'https://i.ibb.co/nDySNMy/Mel-Book-Arab-tili-A5-1-compressed-page-0034.jpg',
    'https://i.ibb.co/nQFM5jh/Mel-Book-Arab-tili-A5-1-compressed-page-0035.jpg',
    'https://i.ibb.co/wB8cn9d/Mel-Book-Arab-tili-A5-1-compressed-page-0036.jpg',
    'https://i.ibb.co/5Wt4jY9/Mel-Book-Arab-tili-A5-1-compressed-page-0037.jpg',
    'https://i.ibb.co/f1Th3rG/Mel-Book-Arab-tili-A5-1-compressed-page-0038.jpg',
    'https://i.ibb.co/Tb0JBJQ/Mel-Book-Arab-tili-A5-1-compressed-page-0039.jpg',
    'https://i.ibb.co/KX6T29p/Mel-Book-Arab-tili-A5-1-compressed-page-0040.jpg',
    'https://i.ibb.co/xfZW30B/Mel-Book-Arab-tili-A5-1-compressed-page-0041.jpg',
    'https://i.ibb.co/ZcptK0b/Mel-Book-Arab-tili-A5-1-compressed-page-0042.jpg',
    'https://i.ibb.co/KKZVtZh/Mel-Book-Arab-tili-A5-1-compressed-page-0043.jpg',
    'https://i.ibb.co/qpqY4Wc/Mel-Book-Arab-tili-A5-1-compressed-page-0044.jpg',
    'https://i.ibb.co/xhZ30cj/Mel-Book-Arab-tili-A5-1-compressed-page-0045.jpg',
    'https://i.ibb.co/4MW87jF/Mel-Book-Arab-tili-A5-1-compressed-page-0046.jpg',
    'https://i.ibb.co/j5mGxqJ/Mel-Book-Arab-tili-A5-1-compressed-page-0047.jpg',
    'https://i.ibb.co/zVVqC19/Mel-Book-Arab-tili-A5-1-compressed-page-0048.jpg',
    'https://i.ibb.co/C295ksn/Mel-Book-Arab-tili-A5-1-compressed-page-0049.jpg',
    'https://i.ibb.co/ChTC9nG/Mel-Book-Arab-tili-A5-1-compressed-page-0050.jpg',
    'https://i.ibb.co/Y8Gz9Nx/Mel-Book-Arab-tili-A5-1-compressed-page-0051.jpg',
    'https://i.ibb.co/rQvmKq5/Mel-Book-Arab-tili-A5-1-compressed-page-0052.jpg',
    'https://i.ibb.co/4NpVR89/Mel-Book-Arab-tili-A5-1-compressed-page-0053.jpg',
    'https://i.ibb.co/yyFDxS3/Mel-Book-Arab-tili-A5-1-compressed-page-0054.jpg',
    'https://i.ibb.co/gW7wpXW/Mel-Book-Arab-tili-A5-1-compressed-page-0055.jpg',
    'https://i.ibb.co/41MjzVr/Mel-Book-Arab-tili-A5-1-compressed-page-0056.jpg',
    'https://i.ibb.co/8r6Ld1s/Mel-Book-Arab-tili-A5-1-compressed-page-0057.jpg',
    'https://i.ibb.co/QvDGPYC/Mel-Book-Arab-tili-A5-1-compressed-page-0058.jpg',
    'https://i.ibb.co/YbXnc9r/Mel-Book-Arab-tili-A5-1-compressed-page-0059.jpg',
    'https://i.ibb.co/1fJjKFt/Mel-Book-Arab-tili-A5-1-compressed-page-0060.jpg',
    'https://i.ibb.co/kXC1SQs/Mel-Book-Arab-tili-A5-1-compressed-page-0061.jpg',
    'https://i.ibb.co/749PmDp/Mel-Book-Arab-tili-A5-1-compressed-page-0062.jpg',
    'https://i.ibb.co/9vdnqd0/Mel-Book-Arab-tili-A5-1-compressed-page-0063.jpg',
    'https://i.ibb.co/Nxq9nrY/Mel-Book-Arab-tili-A5-1-compressed-page-0064.jpg',
    'https://i.ibb.co/mBpw575/Mel-Book-Arab-tili-A5-1-compressed-page-0065.jpg',
    'https://i.ibb.co/MDPznDP/Mel-Book-Arab-tili-A5-1-compressed-page-0066.jpg',
    'https://i.ibb.co/L8V262z/Mel-Book-Arab-tili-A5-1-compressed-page-0067.jpg',
    'https://i.ibb.co/wS3TqKy/Mel-Book-Arab-tili-A5-1-compressed-page-0068.jpg',
    'https://i.ibb.co/B66z5Zm/Mel-Book-Arab-tili-A5-1-compressed-page-0069.jpg',
    'https://i.ibb.co/vZFvZdL/Mel-Book-Arab-tili-A5-1-compressed-page-0070.jpg',
    'https://i.ibb.co/vHnmjFF/Mel-Book-Arab-tili-A5-1-compressed-page-0071.jpg',
    'https://i.ibb.co/tMTQ0zF/Mel-Book-Arab-tili-A5-1-compressed-page-0072.jpg',
    'https://i.ibb.co/N2zh2XL/Mel-Book-Arab-tili-A5-1-compressed-page-0073.jpg',
    'https://i.ibb.co/bJJq288/Mel-Book-Arab-tili-A5-1-compressed-page-0074.jpg',
    'https://i.ibb.co/mHjrFVM/Mel-Book-Arab-tili-A5-1-compressed-page-0075.jpg',
    'https://i.ibb.co/cNswgkk/Mel-Book-Arab-tili-A5-1-compressed-page-0076.jpg',
    'https://i.ibb.co/72Mjxhd/Mel-Book-Arab-tili-A5-1-compressed-page-0077.jpg',
    'https://i.ibb.co/56jQ9P2/Mel-Book-Arab-tili-A5-1-compressed-page-0078.jpg',
    'https://i.ibb.co/B2swQPQ/Mel-Book-Arab-tili-A5-1-compressed-page-0079.jpg',
    'https://i.ibb.co/7V6dkwx/Mel-Book-Arab-tili-A5-1-compressed-page-0080.jpg',
    'https://i.ibb.co/VSth5Cn/Mel-Book-Arab-tili-A5-1-compressed-page-0081.jpg',
    'https://i.ibb.co/Q60BRc6/Mel-Book-Arab-tili-A5-1-compressed-page-0082.jpg',
    'https://i.ibb.co/XSV6kwD/Mel-Book-Arab-tili-A5-1-compressed-page-0083.jpg',
    'https://i.ibb.co/mNy0tCk/Mel-Book-Arab-tili-A5-1-compressed-page-0084.jpg',
    'https://i.ibb.co/g9fDpcH/Mel-Book-Arab-tili-A5-1-compressed-page-0085.jpg',
    'https://i.ibb.co/nRGxK2t/Mel-Book-Arab-tili-A5-1-compressed-page-0086.jpg',
    'https://i.ibb.co/sjDzhSv/Mel-Book-Arab-tili-A5-1-compressed-page-0087.jpg',
    'https://i.ibb.co/ThPzRBp/Mel-Book-Arab-tili-A5-1-compressed-page-0088.jpg',
    'https://i.ibb.co/n8SgPHr/Mel-Book-Arab-tili-A5-1-compressed-page-0089.jpg',
    'https://i.ibb.co/r0pdmCD/Mel-Book-Arab-tili-A5-1-compressed-page-0090.jpg',
    'https://i.ibb.co/mRrLr8M/Mel-Book-Arab-tili-A5-1-compressed-page-0091.jpg',
    'https://i.ibb.co/w6gzk1h/Mel-Book-Arab-tili-A5-1-compressed-page-0092.jpg',
    'https://i.ibb.co/N3D9XLk/Mel-Book-Arab-tili-A5-1-compressed-page-0093.jpg',
    'https://i.ibb.co/d7XK7vC/Mel-Book-Arab-tili-A5-1-compressed-page-0094.jpg',
    'https://i.ibb.co/8jJHqMN/Mel-Book-Arab-tili-A5-1-compressed-page-0095.jpg',
    'https://i.ibb.co/1GhrG2j/Mel-Book-Arab-tili-A5-1-compressed-page-0096.jpg',
    'https://i.ibb.co/ZK5zGDw/Mel-Book-Arab-tili-A5-1-compressed-page-0097.jpg',
    'https://i.ibb.co/tPVd6qz/Mel-Book-Arab-tili-A5-1-compressed-page-0098.jpg',
    'https://i.ibb.co/cNmkhj0/Mel-Book-Arab-tili-A5-1-compressed-page-0099.jpg',
    'https://i.ibb.co/qgDWvjw/Mel-Book-Arab-tili-A5-1-compressed-page-0100.jpg',
    'https://i.ibb.co/k2zbq4w/Mel-Book-Arab-tili-A5-1-compressed-page-0101.jpg',
    'https://i.ibb.co/MBb5PT3/Mel-Book-Arab-tili-A5-1-compressed-page-0102.jpg',
    'https://i.ibb.co/Dgy1z2c/Mel-Book-Arab-tili-A5-1-compressed-page-0103.jpg',
    'https://i.ibb.co/MPr5yYk/Mel-Book-Arab-tili-A5-1-compressed-page-0104.jpg',
    'https://i.ibb.co/wpsfj3c/Mel-Book-Arab-tili-A5-1-compressed-page-0105.jpg',
    'https://i.ibb.co/SPCY8n2/Mel-Book-Arab-tili-A5-1-compressed-page-0106.jpg',
    'https://i.ibb.co/9rDxz7y/Mel-Book-Arab-tili-A5-1-compressed-page-0107.jpg',
    'https://i.ibb.co/Vg8CPFx/Mel-Book-Arab-tili-A5-1-compressed-page-0108.jpg',
    'https://i.ibb.co/3v75H0B/Mel-Book-Arab-tili-A5-1-compressed-page-0109.jpg',
    'https://i.ibb.co/W0QmdVc/Mel-Book-Arab-tili-A5-1-compressed-page-0110.jpg',
    'https://i.ibb.co/2tcWD5Y/Mel-Book-Arab-tili-A5-1-compressed-page-0111.jpg',
    'https://i.ibb.co/1JhCwbB/Mel-Book-Arab-tili-A5-1-compressed-page-0112.jpg',
    'https://i.ibb.co/BcPxbP3/Mel-Book-Arab-tili-A5-1-compressed-page-0113.jpg',
    'https://i.ibb.co/st42ZhS/Mel-Book-Arab-tili-A5-1-compressed-page-0114.jpg',
    'https://i.ibb.co/ThrVzq5/Mel-Book-Arab-tili-A5-1-compressed-page-0115.jpg',
    'https://i.ibb.co/nMhfFB5/Mel-Book-Arab-tili-A5-1-compressed-page-0116.jpg',
    'https://i.ibb.co/RcD7tdT/Mel-Book-Arab-tili-A5-1-compressed-page-0117.jpg',
    'https://i.ibb.co/gm5XJtq/Mel-Book-Arab-tili-A5-1-compressed-page-0118.jpg',
    'https://i.ibb.co/fMx3C6P/Mel-Book-Arab-tili-A5-1-compressed-page-0119.jpg',
    'https://i.ibb.co/WKQQrGT/Mel-Book-Arab-tili-A5-1-compressed-page-0120.jpg',
    'https://i.ibb.co/N9rVgLv/Mel-Book-Arab-tili-A5-1-compressed-page-0121.jpg',
    'https://i.ibb.co/k3JH9CM/Mel-Book-Arab-tili-A5-1-compressed-page-0122.jpg',
    'https://i.ibb.co/sQJp5nQ/Mel-Book-Arab-tili-A5-1-compressed-page-0123.jpg',
    'https://i.ibb.co/8rNqc6x/Mel-Book-Arab-tili-A5-1-compressed-page-0124.jpg',
    'https://i.ibb.co/7KWFzJn/Mel-Book-Arab-tili-A5-1-compressed-page-0125.jpg',
    'https://i.ibb.co/Q90qfTg/Mel-Book-Arab-tili-A5-1-compressed-page-0126.jpg',
    'https://i.ibb.co/s38YCJR/Mel-Book-Arab-tili-A5-1-compressed-page-0127.jpg',
    'https://i.ibb.co/yFKLZKL/Mel-Book-Arab-tili-A5-1-compressed-page-0128.jpg',
    'https://i.ibb.co/Tcr4jqz/Mel-Book-Arab-tili-A5-1-compressed-page-0129.jpg',
    'https://i.ibb.co/2kFHxtG/Mel-Book-Arab-tili-A5-1-compressed-page-0130.jpg',
    'https://i.ibb.co/QcQzmML/Mel-Book-Arab-tili-A5-1-compressed-page-0131.jpg',
    'https://i.ibb.co/NLyF6M9/Mel-Book-Arab-tili-A5-1-compressed-page-0132.jpg',
    'https://i.ibb.co/hmd82vQ/Mel-Book-Arab-tili-A5-1-compressed-page-0133.jpg',
    'https://i.ibb.co/9NWJHmV/Mel-Book-Arab-tili-A5-1-compressed-page-0134.jpg',
    'https://i.ibb.co/FV9HSpL/Mel-Book-Arab-tili-A5-1-compressed-page-0135.jpg',
    'https://i.ibb.co/dJ9pc0t/Mel-Book-Arab-tili-A5-1-compressed-page-0136.jpg',
    'https://i.ibb.co/sCBF3q0/Mel-Book-Arab-tili-A5-1-compressed-page-0137.jpg',
    'https://i.ibb.co/RSwmP2D/Mel-Book-Arab-tili-A5-1-compressed-page-0138.jpg',
    'https://i.ibb.co/sKBF4r7/Mel-Book-Arab-tili-A5-1-compressed-page-0139.jpg',
    'https://i.ibb.co/xXjtCVg/Mel-Book-Arab-tili-A5-1-compressed-page-0140.jpg',
    'https://i.ibb.co/FY95KFK/Mel-Book-Arab-tili-A5-1-compressed-page-0141.jpg',
    'https://i.ibb.co/SJD6pTC/Mel-Book-Arab-tili-A5-1-compressed-page-0142.jpg',
    'https://i.ibb.co/7JwJjWT/Mel-Book-Arab-tili-A5-1-compressed-page-0143.jpg',
    'https://i.ibb.co/xfjpc1Q/Mel-Book-Arab-tili-A5-1-compressed-page-0144.jpg',
    'https://i.ibb.co/gSpPqFk/Mel-Book-Arab-tili-A5-1-compressed-page-0145.jpg',
    'https://i.ibb.co/qsy40Nd/Mel-Book-Arab-tili-A5-1-compressed-page-0146.jpg',
    'https://i.ibb.co/2yZ6gRS/Mel-Book-Arab-tili-A5-1-compressed-page-0147.jpg',
    'https://i.ibb.co/xHByWj4/Mel-Book-Arab-tili-A5-1-compressed-page-0148.jpg',
    'https://i.ibb.co/vVLJPGg/Mel-Book-Arab-tili-A5-1-compressed-page-0149.jpg',
    'https://i.ibb.co/fqFdHyg/Mel-Book-Arab-tili-A5-1-compressed-page-0150.jpg',
    'https://i.ibb.co/d5WSkMh/Mel-Book-Arab-tili-A5-1-compressed-page-0151.jpg',
    'https://i.ibb.co/XsPTv7D/Mel-Book-Arab-tili-A5-1-compressed-page-0152.jpg',
    'https://i.ibb.co/mN9cDF5/Mel-Book-Arab-tili-A5-1-compressed-page-0153.jpg',
    'https://i.ibb.co/PWs9hY4/Mel-Book-Arab-tili-A5-1-compressed-page-0154.jpg',
    'https://i.ibb.co/1JjSQGf/Mel-Book-Arab-tili-A5-1-compressed-page-0155.jpg',
    'https://i.ibb.co/1XfWkYV/Mel-Book-Arab-tili-A5-1-compressed-page-0156.jpg',
    'https://i.ibb.co/0FKcCGt/Mel-Book-Arab-tili-A5-1-compressed-page-0157.jpg',
    'https://i.ibb.co/h2KFhwz/Mel-Book-Arab-tili-A5-1-compressed-page-0158.jpg',
    'https://i.ibb.co/t3qJNKJ/Mel-Book-Arab-tili-A5-1-compressed-page-0159.jpg',
    'https://i.ibb.co/5xzGHV6/Mel-Book-Arab-tili-A5-1-compressed-page-0160.jpg',
    'https://i.ibb.co/4ZVtYYY/Mel-Book-Arab-tili-A5-1-compressed-page-0161.jpg',
    'https://i.ibb.co/w7Jhjth/Mel-Book-Arab-tili-A5-1-compressed-page-0162.jpg',
    'https://i.ibb.co/G9jBdVy/Mel-Book-Arab-tili-A5-1-compressed-page-0163.jpg',
    'https://i.ibb.co/6vgpQYY/Mel-Book-Arab-tili-A5-1-compressed-page-0164.jpg',
    'https://i.ibb.co/wy6x0Qd/Mel-Book-Arab-tili-A5-1-compressed-page-0165.jpg',
    'https://i.ibb.co/2MxsSrc/Mel-Book-Arab-tili-A5-1-compressed-page-0166.jpg',
    'https://i.ibb.co/tLWCmtj/Mel-Book-Arab-tili-A5-1-compressed-page-0167.jpg',
    'https://i.ibb.co/stzvmD2/Mel-Book-Arab-tili-A5-1-compressed-page-0168.jpg',
    'https://i.ibb.co/F3mHp6b/Mel-Book-Arab-tili-A5-1-compressed-page-0169.jpg',
    'https://i.ibb.co/TvpPNCg/Mel-Book-Arab-tili-A5-1-compressed-page-0170.jpg',
    'https://i.ibb.co/TmmNth0/Mel-Book-Arab-tili-A5-1-compressed-page-0171.jpg',
    'https://i.ibb.co/YT2bhPb/Mel-Book-Arab-tili-A5-1-compressed-page-0172.jpg',
    'https://i.ibb.co/Cty3KTW/Mel-Book-Arab-tili-A5-1-compressed-page-0173.jpg',
    'https://i.ibb.co/xL296ND/Mel-Book-Arab-tili-A5-1-compressed-page-0174.jpg',
    'https://i.ibb.co/4WFcPbB/Mel-Book-Arab-tili-A5-1-compressed-page-0175.jpg',
    'https://i.ibb.co/tmR7rmM/Mel-Book-Arab-tili-A5-1-compressed-page-0176.jpg',
    'https://i.ibb.co/zfw0tbh/Mel-Book-Arab-tili-A5-1-compressed-page-0177.jpg',
    'https://i.ibb.co/DbJtwYS/Mel-Book-Arab-tili-A5-1-compressed-page-0178.jpg',
    'https://i.ibb.co/8sfw0nz/Mel-Book-Arab-tili-A5-1-compressed-page-0179.jpg',
    'https://i.ibb.co/YNKR9JL/Mel-Book-Arab-tili-A5-1-compressed-page-0180.jpg',
    'https://i.ibb.co/4MZBGkQ/Mel-Book-Arab-tili-A5-1-compressed-page-0181.jpg',
    'https://i.ibb.co/9TS1PnH/Mel-Book-Arab-tili-A5-1-compressed-page-0182.jpg',
    'https://i.ibb.co/gJ01jWd/Mel-Book-Arab-tili-A5-1-compressed-page-0183.jpg',
    'https://i.ibb.co/RzbL6g8/Mel-Book-Arab-tili-A5-1-compressed-page-0184.jpg',
    'https://i.ibb.co/6Y9YzXy/Mel-Book-Arab-tili-A5-1-compressed-page-0185.jpg',
    'https://i.ibb.co/6vTZLXd/Mel-Book-Arab-tili-A5-1-compressed-page-0186.jpg',
    'https://i.ibb.co/WFP1NKm/Mel-Book-Arab-tili-A5-1-compressed-page-0187.jpg',
    'https://i.ibb.co/L1Sr2k2/Mel-Book-Arab-tili-A5-1-compressed-page-0188.jpg',
    'https://i.ibb.co/4Rg3fgL/Mel-Book-Arab-tili-A5-1-compressed-page-0189.jpg',
    'https://i.ibb.co/DYbT05B/Mel-Book-Arab-tili-A5-1-compressed-page-0190.jpg',
    'https://i.ibb.co/TmnLDCq/Mel-Book-Arab-tili-A5-1-compressed-page-0191.jpg',
    'https://i.ibb.co/ZGG80zM/Mel-Book-Arab-tili-A5-1-compressed-page-0192.jpg',
    'https://i.ibb.co/TPHvWDV/Mel-Book-Arab-tili-A5-1-compressed-page-0193.jpg',
    'https://i.ibb.co/YWRbGjB/Mel-Book-Arab-tili-A5-1-compressed-page-0194.jpg',
    'https://i.ibb.co/FHRKMSv/Mel-Book-Arab-tili-A5-1-compressed-page-0195.jpg',
    'https://i.ibb.co/d2JM5Rw/Mel-Book-Arab-tili-A5-1-compressed-page-0196.jpg',
    'https://i.ibb.co/JCDtqCv/Mel-Book-Arab-tili-A5-1-compressed-page-0197.jpg',
    'https://i.ibb.co/yWRb2yG/Mel-Book-Arab-tili-A5-1-compressed-page-0198.jpg',
    'https://i.ibb.co/NyQkmSD/Mel-Book-Arab-tili-A5-1-compressed-page-0199.jpg',
    'https://i.ibb.co/XZZ5Fw4/Mel-Book-Arab-tili-A5-1-compressed-page-0200.jpg',
    'https://i.ibb.co/QYQ80N1/Mel-Book-Arab-tili-A5-1-compressed-page-0201.jpg',
    'https://i.ibb.co/3B6qRgN/Mel-Book-Arab-tili-A5-1-compressed-page-0202.jpg',
    'https://i.ibb.co/mJb8R70/Mel-Book-Arab-tili-A5-1-compressed-page-0203.jpg',
    'https://i.ibb.co/L065f30/Mel-Book-Arab-tili-A5-1-compressed-page-0204.jpg',
    'https://i.ibb.co/BcZCC9H/Mel-Book-Arab-tili-A5-1-compressed-page-0205.jpg',
    'https://i.ibb.co/S5bGGfz/Mel-Book-Arab-tili-A5-1-compressed-page-0206.jpg',
    'https://i.ibb.co/2KBB8Cr/Mel-Book-Arab-tili-A5-1-compressed-page-0207.jpg',
    'https://i.ibb.co/x6txH12/Mel-Book-Arab-tili-A5-1-compressed-page-0208.jpg',
    'https://i.ibb.co/Nxgk9K4/Mel-Book-Arab-tili-A5-1-compressed-page-0209.jpg',
    'https://i.ibb.co/WBYRnPJ/Mel-Book-Arab-tili-A5-1-compressed-page-0210.jpg',
    'https://i.ibb.co/C0fbvCQ/Mel-Book-Arab-tili-A5-1-compressed-page-0211.jpg',
    'https://i.ibb.co/7Q5Pz0j/Mel-Book-Arab-tili-A5-1-compressed-page-0212.jpg',
    'https://i.ibb.co/BN8pkpQ/Mel-Book-Arab-tili-A5-1-compressed-page-0213.jpg',
    'https://i.ibb.co/pWC0pSL/Mel-Book-Arab-tili-A5-1-compressed-page-0214.jpg',
    'https://i.ibb.co/jkDMLfw/Mel-Book-Arab-tili-A5-1-compressed-page-0215.jpg',
    'https://i.ibb.co/HgC0Xbx/Mel-Book-Arab-tili-A5-1-compressed-page-0216.jpg',
    'https://i.ibb.co/dD9yCZc/Mel-Book-Arab-tili-A5-1-compressed-page-0217.jpg',
    'https://i.ibb.co/V9RbfHg/Mel-Book-Arab-tili-A5-1-compressed-page-0218.jpg',
    'https://i.ibb.co/JsmkYn1/Mel-Book-Arab-tili-A5-1-compressed-page-0219.jpg',
    'https://i.ibb.co/XpTSc83/Mel-Book-Arab-tili-A5-1-compressed-page-0220.jpg',
    'https://i.ibb.co/02fX9Vr/Mel-Book-Arab-tili-A5-1-compressed-page-0221.jpg',
    'https://i.ibb.co/D1522qg/Mel-Book-Arab-tili-A5-1-compressed-page-0222.jpg',
    'https://i.ibb.co/GdTGjkt/Mel-Book-Arab-tili-A5-1-compressed-page-0223.jpg',
    'https://i.ibb.co/Thg6f0Y/Mel-Book-Arab-tili-A5-1-compressed-page-0224.jpg',
    'https://i.ibb.co/sVdmsvp/Mel-Book-Arab-tili-A5-1-compressed-page-0225.jpg',
    'https://i.ibb.co/w4R2MRZ/Mel-Book-Arab-tili-A5-1-compressed-page-0226.jpg',
    'https://i.ibb.co/2t2CNyb/Mel-Book-Arab-tili-A5-1-compressed-page-0227.jpg',
    'https://i.ibb.co/tJwgy7Y/Mel-Book-Arab-tili-A5-1-compressed-page-0228.jpg',
    'https://i.ibb.co/9sDQQKK/Mel-Book-Arab-tili-A5-1-compressed-page-0229.jpg',
    'https://i.ibb.co/g69Tw4R/Mel-Book-Arab-tili-A5-1-compressed-page-0230.jpg',
    'https://i.ibb.co/5Wzfjxn/Mel-Book-Arab-tili-A5-1-compressed-page-0231.jpg',
    'https://i.ibb.co/jMLMTw9/Mel-Book-Arab-tili-A5-1-compressed-page-0232.jpg',
    'https://i.ibb.co/ZXTZXdb/Mel-Book-Arab-tili-A5-1-compressed-page-0233.jpg',
    'https://i.ibb.co/ZLbfx67/Mel-Book-Arab-tili-A5-1-compressed-page-0234.jpg',
    'https://i.ibb.co/QcRyZsC/Mel-Book-Arab-tili-A5-1-compressed-page-0235.jpg',
    'https://i.ibb.co/vkhtx4K/Mel-Book-Arab-tili-A5-1-compressed-page-0236.jpg',
    'https://i.ibb.co/yPNTYwh/Mel-Book-Arab-tili-A5-1-compressed-page-0237.jpg',
    'https://i.ibb.co/FnjR25f/Mel-Book-Arab-tili-A5-1-compressed-page-0238.jpg',
    'https://i.ibb.co/2KB4xcB/Mel-Book-Arab-tili-A5-1-compressed-page-0239.jpg',
    'https://i.ibb.co/3k5HsNM/Mel-Book-Arab-tili-A5-1-compressed-page-0240.jpg',
    'https://i.ibb.co/CbxtyRc/Mel-Book-Arab-tili-A5-1-compressed-page-0241.jpg',
    'https://i.ibb.co/tZm2LpP/Mel-Book-Arab-tili-A5-1-compressed-page-0242.jpg',
    'https://i.ibb.co/vQQs3MV/Mel-Book-Arab-tili-A5-1-compressed-page-0243.jpg',
    'https://i.ibb.co/gz4Kvn8/Mel-Book-Arab-tili-A5-1-compressed-page-0244.jpg',
    'https://i.ibb.co/bRNbjKM/Mel-Book-Arab-tili-A5-1-compressed-page-0245.jpg',
    'https://i.ibb.co/brN1yLV/Mel-Book-Arab-tili-A5-1-compressed-page-0246.jpg',
    'https://i.ibb.co/5LZGRGQ/Mel-Book-Arab-tili-A5-1-compressed-page-0247.jpg',
    'https://i.ibb.co/kqXq3dY/Mel-Book-Arab-tili-A5-1-compressed-page-0248.jpg',
    'https://i.ibb.co/dmLZVyR/Mel-Book-Arab-tili-A5-1-compressed-page-0249.jpg',
    'https://i.ibb.co/W2TgJG8/Mel-Book-Arab-tili-A5-1-compressed-page-0250.jpg',
    'https://i.ibb.co/MhTLCpM/Mel-Book-Arab-tili-A5-1-compressed-page-0251.jpg',
    'https://i.ibb.co/0jCpcqC/Mel-Book-Arab-tili-A5-1-compressed-page-0252.jpg',
    'https://i.ibb.co/b1hbG96/Mel-Book-Arab-tili-A5-1-compressed-page-0253.jpg',
    'https://i.ibb.co/f0t6tkL/Mel-Book-Arab-tili-A5-1-compressed-page-0254.jpg',
    'https://i.ibb.co/1n6S2sk/Mel-Book-Arab-tili-A5-1-compressed-page-0255.jpg',
    'https://i.ibb.co/qFyjdnW/Mel-Book-Arab-tili-A5-1-compressed-page-0256.jpg',
    'https://i.ibb.co/yf6JgFR/Mel-Book-Arab-tili-A5-1-compressed-page-0257.jpg',
    'https://i.ibb.co/vsWHrxG/Mel-Book-Arab-tili-A5-1-compressed-page-0258.jpg',
    'https://i.ibb.co/RHmXqZD/Mel-Book-Arab-tili-A5-1-compressed-page-0259.jpg',
    'https://i.ibb.co/nBpCV5B/Mel-Book-Arab-tili-A5-1-compressed-page-0260.jpg',
    'https://i.ibb.co/5Ls11G5/Mel-Book-Arab-tili-A5-1-compressed-page-0261.jpg',
    'https://i.ibb.co/ZJ2sm0x/Mel-Book-Arab-tili-A5-1-compressed-page-0262.jpg',
    'https://i.ibb.co/tDZKXC8/Mel-Book-Arab-tili-A5-1-compressed-page-0263.jpg',
    'https://i.ibb.co/bH39q0R/Mel-Book-Arab-tili-A5-1-compressed-page-0264.jpg',
    'https://i.ibb.co/r7NmfbM/Mel-Book-Arab-tili-A5-1-compressed-page-0265.jpg',
    'https://i.ibb.co/PmnM2Ln/Mel-Book-Arab-tili-A5-1-compressed-page-0266.jpg',
    'https://i.ibb.co/KGy042x/Mel-Book-Arab-tili-A5-1-compressed-page-0267.jpg',
    'https://i.ibb.co/sFVYKkM/Mel-Book-Arab-tili-A5-1-compressed-page-0268.jpg',
    'https://i.ibb.co/7jfnK5X/Mel-Book-Arab-tili-A5-1-compressed-page-0269.jpg',
    'https://i.ibb.co/7gP2DK7/Mel-Book-Arab-tili-A5-1-compressed-page-0270.jpg',
    'https://i.ibb.co/kQ6K3Ws/Mel-Book-Arab-tili-A5-1-compressed-page-0271.jpg',
    'https://i.ibb.co/nCDkZcZ/Mel-Book-Arab-tili-A5-1-compressed-page-0272.jpg',
    'https://i.ibb.co/n6qvTVf/Mel-Book-Arab-tili-A5-1-compressed-page-0273.jpg',
    'https://i.ibb.co/yyWdryW/Mel-Book-Arab-tili-A5-1-compressed-page-0274.jpg',
    'https://i.ibb.co/s5tvzRk/Mel-Book-Arab-tili-A5-1-compressed-page-0275.jpg',
    'https://i.ibb.co/NTyTJCq/Mel-Book-Arab-tili-A5-1-compressed-page-0276.jpg',
    'https://i.ibb.co/2YYqHCS/Mel-Book-Arab-tili-A5-1-compressed-page-0277.jpg',
    'https://i.ibb.co/Fx4Y725/Mel-Book-Arab-tili-A5-1-compressed-page-0278.jpg',
    'https://i.ibb.co/XJVKS9J/Mel-Book-Arab-tili-A5-1-compressed-page-0279.jpg',
    'https://i.ibb.co/vh0Cy3v/Mel-Book-Arab-tili-A5-1-compressed-page-0280.jpg',
    'https://i.ibb.co/3r6NPZ4/Mel-Book-Arab-tili-A5-1-compressed-page-0281.jpg',
    'https://i.ibb.co/MBk1vnR/Mel-Book-Arab-tili-A5-1-compressed-page-0282.jpg',
    'https://i.ibb.co/qFxYpgB/Mel-Book-Arab-tili-A5-1-compressed-page-0283.jpg',
    'https://i.ibb.co/851JnS0/Mel-Book-Arab-tili-A5-1-compressed-page-0284.jpg',
    'https://i.ibb.co/6sXKMYP/Mel-Book-Arab-tili-A5-1-compressed-page-0285.jpg',
    'https://i.ibb.co/xF9ft2L/Mel-Book-Arab-tili-A5-1-compressed-page-0286.jpg',
    'https://i.ibb.co/PcMk7Sw/Mel-Book-Arab-tili-A5-1-compressed-page-0287.jpg',
    'https://i.ibb.co/FzYWtCS/Mel-Book-Arab-tili-A5-1-compressed-page-0288.jpg',
  ];
  @override
  Widget build(BuildContext context) {
    ScreenUtil.init(
      context,
      designSize: Size(360, 690),
      minTextAdapt: true,
    );
    if (widget.page < 0 || widget.page >= images.length){
      return Scaffold(
        backgroundColor: Colors.white,
        body: SafeArea(
          child: Center(
            child: Text('Varoq indexi yetarli emas'),
          ),
        ),
      );
    }
    return Scaffold(
      backgroundColor: Colors.white,
      body: SafeArea(
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              SizedBox(height: 32.h),
              Container(
                height: 1.sh - 140.h,
                width: 1.sw,
                child: CachedNetworkImage(
                  imageUrl: images[widget.page],
                  fit: BoxFit.cover,
                  placeholder: (context, url) => Center(child: CircularProgressIndicator()),
                  errorWidget: (context, url, error) => Center(child: Icon(Icons.error)),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
}